In [1]:
# home llms, office olm2
import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning, message=".*escape sequence.*")

import httpx
from openai import OpenAI
import time
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv, find_dotenv
from statistics import mode
import ast
import re

#from aux_prompts import *
#from queries import criteria_text3
os.environ["OPENAI_API_KEY"] = 'hey' # for importing trialmind, api_key should be set beforehand
os.environ['TEMPERATURE'] = '0'

use = 'rogozin'
#use = 'cpp'

if use == 'hf':
    os.environ["BASE_URL"] = "https://router.huggingface.co/v1"
    os.environ["MODEL_NAME"] ='Qwen/Qwen3-14B'
    os.environ["OPENAI_API_KEY"] = os.getenv("HUGGINGFACE_HUB_TOKEN")
elif use == 'olm':
    os.environ["BASE_URL"] = "http://localhost:11434/v1"
    os.environ["MODEL_NAME"] ='qwen3:14b'
    os.environ["OPENAI_API_KEY"] = 'hey'
elif use == 'rogozin':
    os.environ["BASE_URL"] = "http://localhost:8501/v1"
    os.environ["MODEL_NAME"] ='/models/Qwen3.6-27B-UD-Q4_K_XL.gguf'#'ggml-org/gemma-3-1b-it-GGUF'
    os.environ["TRANSL_MODEL_NAME"] = '/models/Qwen3.6-27B-UD-Q4_K_XL.gguf'
    os.environ["OPENAI_API_KEY"] = 'hello'
elif use == 'sirius':
    os.environ["BASE_URL"] = "http://127.0.0.1:8082/v1"
    os.environ["MODEL_NAME"] ='Qwen3.6-27B'#'ggml-org/gemma-3-1b-it-GGUF'
    os.environ["OPENAI_API_KEY"] = 'hello'
    os.environ["TRANSL_MODEL_NAME"] = 'Qwen3.6-27B'
elif use == 'cloud':
    os.environ["BASE_URL"] = "http://51.250.66.187:8080/v1"
    os.environ["MODEL_NAME"] ='Qwen3.6-27B'
    #os.environ["TRANSL_MODEL_NAME"] = 'gemma-4-12B'
    os.environ["OPENAI_API_KEY"] = 'hey'
load_dotenv(find_dotenv(usecwd=True), override=True)
import glob
import main

%load_ext autoreload
%autoreload 2

c:\Users\MKoshkareva\miniconda3\envs\my_project\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

### small fixes

In [22]:
dfo = pd.read_csv('new_criteria_ana_en.csv')
dfo.PMID = dfo.PMID.apply(lambda x: str(x.split('/')[-1]))
print(dfo.shape)

dfe = pd.read_csv('common_errors_fixed.csv')
dfe['PMID_статьи'] = dfe['PMID_статьи'].apply(lambda x: str(x).split('.')[0])

def fix(x):
    if x['PMID'] in dfe['PMID_статьи'].values:
        row = dfe[dfe['PMID_статьи'] == x['PMID']]
        row_1 =  row[row['Номер_критерия']==1]
        row_2 =  row[row['Номер_критерия']==2]
        row_3 =  row[row['Номер_критерия']==3]
        for row_i in [row_1,row_2,row_3]:
            if row_i.shape[0]:
                i = str(row_i['Номер_критерия'].values[0]).split('.')[0]
                x[f's{i}'] = row_i['Оценка_Эксперт'].values[0]
                x[f'r{i}'] = row_i['Обоснование_Эксперт'].values[0]
                print('change', x['PMID'])
        return x
    else:
        return x

dfo = dfo.apply(lambda x: fix(x), axis=1)
ps_thresh = [1,1,0]
chosen_df = dfo[(dfo['s1']>=ps_thresh[0]
                    )&(dfo['s2']>=ps_thresh[1]
                        )&(dfo['s3']>=ps_thresh[2])]
dfo['accept'] = dfo[['s1','s2','s3']].apply(lambda x: True if (x['s1']>=ps_thresh[0]
                    )&(x['s2']>=ps_thresh[1]
                        )&(x['s3']>=ps_thresh[2]) else False, axis=1)

dfo.accept.value_counts()

(67, 7)
change 25139705
change 31399568
change 26995877
change 35343863
change 35343863
change 26438251
change 26438251
change 37773318
change 37773318
change 37773318
change 33676682
change 23719267
change 23719267
change 22845480
change 24789362
change 37686423
change 41213063
change 41213063
change 36801912
change 28465216
change 28465216
change 36129915
change 36627781
change 36627781
change 34898475
change 34898475
change 28903995
change 28903995
change 23585220
change 26468446
change 23656699
change 29466887
change 40526090
change 40526090
change 38378070

accept
False    40
True     27
Name: count, dtype: int64

In [23]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text = (dfo.iloc[:,4:-1].values).reshape(-1)
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

ImportError: cannot import name 'SyncTranslator' from 'googletrans' (c:\Users\MKoshkareva\miniconda3\envs\my_project\Lib\site-packages\googletrans\__init__.py)

In [ ]:
dfo.iloc[:,4:-1] = np.array([i.text for i in r]).reshape(-1,3)
#dfo.to_csv('new_criteria_ana_en2.csv',index=False)

In [ ]:
dfo.iloc[:,4:-1].values

array([['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
        'Crizotinib has been used to treat mesothelioma',
        'The effectiveness of crizotinib for CRC has not been assessed.'],
       ['"16 colorectal cancer cases"',
        'The abstract states that patients received inhibitors of various signaling pathways, including ALK/ROS1. Although crizotinib is an ALK/ROS1 inhibitor, it is not explicitly named in the abstract. We cannot confirm that it was the specific drug used in patients (it could be ceritinib, alectinib, lorlatinib, etc.)',
        'The abstract provides general data for the cohort (4 patients with CRC had a response), but is not linked to a specific drug.'],
       ['This is a review article summarizing current advances in targeted therapy for solid tumors. It does not include original patients, models or samples',
        'Crizotinib is mentioned in the abstract, but in association with NSCLC',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['The study uses the CRC cell line Colo205 and related animal tumor models',
        'It is stated that crizotinib (both monotherapy and combination) was used to evaluate the effect on metastasis, and this effect was observed in all models tested, including Colo205',
        'The study evaluates the biologically and clinically relevant preclinical outcome of reduced metastasis'],
       ['The abstract mentions CRC as one example of tumors where ROS1 rearrangements may be observed',
        'Crizotinib is mentioned as a drug to which patients have developed resistance',
        'The study evaluates the effectiveness of the new drug DS-6051b, not crizotinib'],
       ['CRC is mentioned as an example ("KRAS against the use of cetuximab and panitumumab in colorectal cancer")',
        'Crizotinib mentioned in the context of NSCLC and ALK fusions',
        'The article does not evaluate the effectiveness of crizotinib in CRC'],
       ['A cohort of 1889 CRC samples is analyzed',
        'Crizotinib is mentioned in the introduction as a drug that has shown good results in the treatment of lung cancer with ALK/ROS1 rearrangements',
        'Therapeutic efficacy assessment for CRC is not available'],
       ['CRC cell line - KM12SM ("the KM12SM colorectal cancer cells containing the TPM3-NTRK1 gene fusion"). Corresponding animal models are also used (“in in vivo KM12SM cell models”)',
        'In vitro: "KM12SM cells were sensitive to the tropomyosin-related kinase-A inhibitors crizotinib and entrectinib". In vivo: "in in vivo KM12SM cell models, treatment with crizotinib delayed the progression of liver metastases..."',
        'The antitumor activity of crizotinib in the CRC model (KM12SM) is assessed by delaying the progression of metastases: “treatment with crizotinib delayed the progression of liver metastases, but not that of brain tumors”'],
       ['"human colorectal cancer (CRC) cell line (HCA-7)"; "CRC tissue microarray"',
        '"Addition of the dual MET/RON tyrosine kinase inhibitor, crizotinib, restored cetuximab sensitivity in SC." Crizotinib is used to overcome cetuximab resistance in a CRC model',
        'Evaluates the therapeutic efficacy of crizotinib based on the biologically significant outcome of “restored cetuximab sensitivity in SC.”'],
       ['CRC is mentioned only once in the introduction as an example of a disease associated with ROS1 ("which is involved in the formation of non-small cell lung cancer (NSCLC), gastric adenocarcinoma, colorectal cancer, and other malignant tumors")',
        'Crizotinib is mentioned in the context of treatment of NSCLC: 1. "only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC" 2. "Since the approval of crizotinib as multi-targeted ALK/MET/ROS1 kinase inhibitor for ALK-mutated NSCLC therapy"',
        'All discussion of the effectiveness of crizotinib applies to NSCLC'],
       ['The title refers to a patient with metastatic colorectal cancer: "Metastatic Colorectal Carcinoma Patient". There is a description of a patient with CRC',
        'Crizotinib (along with Alectinib and Lorlatinib) was used as a treatment for the patient: "Clinical Responses to Crizotinib, Alectinib, and Lorlatinib..."',
        'The name indicates "Clinical Responses", which involves assessing clinical response. However, without an abstract it is impossible to confirm: Which outcomes were assessed (ORR, PFS, OS, etc.); Was quantitative data provided; What was the specific response to crizotinib (given that there are three drugs mentioned in the title)'],
       ['CRC is mentioned once in the introduction as an example of a disease associated with ROS1: "ROS1 plays an important role in different malignancies including glioblastoma, colorectal cancer, gastric adenocarcinoma..."',
        'Crizotinib is mentioned exclusively in the context of the treatment of lung cancer: "After Crizotinib approval by FDA for the management of ALK-rearranged lung cancer..."',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['CRC is mentioned in the list of tumors in which ALK inhibitor activity is described ("colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer"), but this is only a mention in the list, and not the subject of primary research',
        'The review does not specifically target crizotinib for colorectal cancer - it is a review where CRC is just one of many tumor types mentioned. Without the full text, it is unclear how much detail the use of crizotinib in CRC is covered',
        'The abstract provides response rates (~50-85%), but these relate to approved indications (NSCLC, IMT, ALCL), not CRC'],
       ['The current study includes patients with a mixed population of solid tumors, not focusing on CRC. Although the Background section mentions a previous study on CRC xenografts (“We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth”). The Methods section states: "patients with advanced solid tumors received PD-0325901 with crizotinib" - without mentioning CRC as a specific population',
        'There is no indication in the abstract that the 25 patients included patients with CRC or that CRC was the target indication. Crizotinib used in combination with PD-0325901 in a mixed population',
        'Evaluates the effectiveness of the PD-0325901/crizotinib combination for solid tumors in general: "The best clinical response was stable disease in seven patients (29%)." Outcome is presented for the entire cohort, without breakdown by tumor type'],
       ['CRC cells in vitro (“specifically binds to c-Met in CRC cells”), mice with CRC tumors in vivo (“c-Met positive tumor-bearing mice”), etc.',
        'Used as a structural basis for the creation of a diagnostic fluorescent probe Crizotinib-PEG4-MPA. The text states: "we have developed a new small molecular fluorescence probe, namely Crizotinib-PEG4-MPA" - this is a modified molecule where crizotinib serves as a targeting element for binding to c-Met, but not as an independent drug for treatment',
        'The diagnostic effectiveness of the fluorescent probe is assessed, not the therapeutic effectiveness'],
       ['"We analyzed 26 MSI-High and 558 non-MSI-High CRC tumors", "We tested CRC cell lines", "Using an in-vivo CRC xenograft model"',
        '"tested CRC cell lines for sensitivity to MMC plus crizotinib" и "combined crizotinib and MMC therapy"',
        'In vitro:"increased apoptosis" и "synergistic anti-cancer effect (CI = 0.006-0.74)" In vivo: "reduced tumor growth with combined crizotinib and MMC therapy (p = 0.0088)"'],
       ['CRC is mentioned once in the list of diseases associated with ROS1 rearrangements: "including glioblastoma, non-small cell lung cancer (NSCLC), cholangiocarcinoma, ovarian cancer, gastric adenocarcinoma, colorectal cancer, inflammatory myofibroblastic tumor, angiosarcoma, and epithelioid hemangioendothelioma"',
        'Crizotinib is mentioned in the context of lung cancer treatment: "Targeting ROS1 fusion proteins with the small-molecule inhibitor crizotinib is showing promise as an effective therapy in patients with NSCLC whose tumors are positive for these genetic abnormalities."',
        'The article does not describe the assessment of the therapeutic efficacy of crizotinib in the treatment of colorectal cancer'],
       ['"colorectal cancer (CRC) cell lines" и "metastatic and orthotopic animal models of colon cancer"',
        '"combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib)" на моделях CRC',
        '"significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer"'],
       ['Among the responders, patients with CRC were mentioned, but the study did not focus on them. There are no separate models, cell lines or detailed analysis of only this group',
        'Crizotinib is not mentioned in the abstract. Study Evaluates Entrechtinib',
        'The study is evaluating entrechtinib. There is simply no data on the therapeutic efficacy of crizotinib for CRC.'],
       ['Human colon carcinoma cells and animal models were used',
        'It was indicated that inhibition of the MTH1 enzyme with (S)-crizotinib caused an increase in single-strand DNA breaks and activated DNA repair in human colon carcinoma cells',
        '1) increase in single-strand DNA breaks and activation of DNA repair in colon carcinoma cells 2) effective suppression of tumor growth in animal models'],
       ['CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab. The object being studied is biomarkers, not diseases',
        'Crizotinib is mentioned in the abstract, but exclusively in relation to non-small cell lung cancer and the EML4-ALK biomarker',
        'All discussions of the effectiveness of crizotinib apply to NSCLC'],
       ['CRC is mentioned once in the list of examples: "the use of the monoclonal antibodies (trastuzumab and cetuximab) in HER2-positive breast cancer and wild-type KRAS colorectal cancer"',
        'Crizotinib in the article is associated with CML, GIST and NSCLC',
        'Crizotinib is not being studied for CRC. The article cannot evaluate its therapeutic effectiveness'],
       ['CRC is mentioned once in the introduction as a general example of malignancies in which rearrangements of receptor tyrosine kinases have been described',
        'Crizotinib is mentioned in the Background section in the context of treating NSCLC',
        'The conclusion makes a general conclusion about the feasibility of studying ROS1 inhibitors (without specifying a specific drug) for a subgroup of patients with gastric cancer'],
       ['CRC is mentioned as one of the three main tumor types considered in the context of a review of approved drugs (bevacizumab, cetuximab), without presenting its own primary data or models',
        '"FDA-approved drugs like osimertinib and crizotinib... providing remarkable benefits in patients with EGFR-mutated or ALK-positive lung cancer"',
        'All efficacy data mentioned are for either lung cancer (for crizotinib) or CRC (for bevacizumab and cetuximab)'],
       ['The study focused on CRC. It uses the TCGA and GEO databases containing samples from patients with CRC ("The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival")',
        '"Immunonomic environment analysis, immunotherapy response prediction, enrichment analysis, tumor mutation analysis and drug prediction were performed in risk groups." The potential sensitivity of crizotinib was mathematically modeled',
        'The study provides predicted sensitivity but does not report any biologically or clinically relevant outcomes (such as apoptosis, tumor growth inhibition, survival, etc.) in response to crizotinib'],
       ['The study uses clinically relevant models - 3D CRC cultures ("patient-derived 3D colorectal cancer cultures")',
        'Study testing (S)-enantiomer of crizotinib as an intervention in 3D CRC cultures',
        'Эффективность: "reduce cancer cell viability"; "reduced tyrosine phosphorylation of c-MET and ErbB3"; "induced DNA damage"'],
       ['"A patient with metastatic BRAF-mutated colorectal cancer" и "In BRAF-mutated colorectal cancer cells"',
        '"the patient was treated with the dual ALK-MET inhibitor crizotinib plus vemurafenib"',
        'Clinical outcome: The patient had a rapid and robust clinical response to the new therapy regimen. Biological/preclinical outcome: The combination of BRAF and MET inhibition (crizotinib) was shown in vitro to overcome acquired resistance to previous therapy'],
       ['Study describes inflammatory myofibroblastic tumor',
        'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['Study focused on CRC',
        'Crizotinib is being investigated as the active therapeutic component of the Crizotinib-IR808 conjugate. The conjugate is used for chemophototherapy, where crizotinib acts as a chemotherapeutic agent in combination with phototherapy',
        'Study evaluates therapeutic efficacy of crizotinib-containing conjugate based on biologically relevant preclinical outcomes'],
       ['Study describes a patient with an inflammatory myofibroblastic tumor of the rectoanal region',
        'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['"the TRKA-dependent colorectal carcinoma KM12"; "Oral administration of entrectinib to tumor-bearing mice induced regression in relevant human xenograft tumors, including the TRKA-dependent colorectal carcinoma KM12"; "objective responses to a TRK inhibitor in colorectal carcinoma"',
        'Crizotinib is mentioned as an example of an already known selective kinase inhibitor, the effectiveness of which has been demonstrated in ALK/ROS1-positive tumors: "selective kinase inhibitors such as crizotinib, ceritinib, and alectinib"',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['CRC is mentioned once in the abstract in the context that combined BRAF+MEK inhibition is not approved for it (“FDA approved for BRAF V600E-mutant solid tumors except for colorectal cancer”)',
        'Crizotinib is being studied in combination with vemurafenib in the general population (solid tumors in general)',
        'Study evaluates OS, PFS and ORR for entire solid tumor cohort'],
       ['"The LoVo colon cancer cell line"',
        'Crizotinib applied as an experimental treatment to CRC spheroids',
        'The study evaluates the biological effect of crizotinib in a 3D model of CRC. Although the focus of the article is on validating a new measurement method, the authors demonstrate that treatment with crizotinib has an effect on the biological parameters of the spheroids (changes in mass density and, as a result, structural integrity).'],
       ['The study included two independent clinical cohorts of patients with CRC (n=363 and n=390), clinical tissue samples ("clinical CRC tissues"), and also included cellular models to assess migration and invasion',
        '"the c-MET inhibitor crizotinib blocked the HGF/STAT3/SOX13/c-MET axis"',
        '"significantly inhibiting SOX13-mediated CRC migration, invasion and metastasis"'],
       ['The study focuses on hepatocellular carcinoma',
        'Crizotinib is being used and is being studied as an intervention for hepatocellular carcinoma',
        'Because the study does not include CRC nor does it test crizotinib, its therapeutic efficacy for CRC cannot be assessed.'],
       ['CRC is mentioned once in the list of rare locations where ROS1 fusions can occur',
        '"Crizotinib was the first inhibitor approved... for the treatment of ROS1-positive non-small cell lung cancer"',
        'The article does not evaluate the effectiveness of crizotinib in CRC'],
       ['Uses a tissue microarray of colorectal tumors, as well as 3 well-known CRC cell lines with the KRAS mutation: HCT116, DLD1 and LoVo',
        '"used a small molecule inhibitor of c-Met, crizotinib, in cetuximab-resistant, mutant KRAS-driven colorectal cancer cell lines"',
        'The study evaluates biologically and clinically relevant outcomes of crizotinib in combination with radiation. Specific quantitative data provided'],
       ['Research about CRC. It uses data from The Cancer Genome Atlas (TCGA) specifically for the PTPRK-RSPO3 fusion CRC subtype',
        'Crizotinib was identified through bioinformatics analysis of target-drug networks.',
        'Therapeutic efficacy has not been assessed'],
       ['"RNA sequencing of formalin-fixed, paraffin-embedded (FFPE) cancer tissue samples of 23 CRC patients"',
        '"Patients were treated by... crizotinib... as monotherapy or in combination with chemotherapy"',
        'The abstract provides algorithm quality metrics (AUC, Hazard ratio) for bevacizumab, but does not provide specific data on the actual therapeutic efficacy of crizotinib (for example, ORR, PFS or OS specifically for the crizotinib-treated cohort). The abstract does not allow an unambiguous assessment of the clinical efficacy of crizotinib as such.'],
       ['CRC is mentioned once in the list of diseases in the pathogenesis of which ALK may play a role',
        'Crizotinib is mentioned in the context of treating NSCLC',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['"Thirty-six RASMT metastatic CRC patients were enrolled in the dose expansion"',
        '"assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients"',
        'Эффективность: "Best clinical response within the RASMT CRC cohort was stable disease in seven patients (24%)", "no objective responses observed"'],
       ['"expression profiles and clinical characteristics of CRC from the Gene Expression Omnibus (GEO) database and the Cancer Genome Atlas (TCGA) database"',
        'The drug is mathematically predicted to be potentially effective for a subgroup of patients at high immune risk (“S-crizotinib might have potential therapeutic implications”)',
        'Therapeutic efficacy has not been assessed'],
       ['The study represents a general screen of 1402 chemical compounds for their immunomodulatory potential ex vivo on peripheral mononuclear leukocytes. Although T cell interaction with "cancer cells" is mentioned, there is no indication in the abstract that these are CRC cells',
        'Crizotinib is being studied for its immunomodulatory properties (the ability to alter interactions between cells of the immune system)',
        'The study evaluates the effect of crizotinib on immune interactions rather than antitumor activity'],
       ['"human epithelial colorectal adenocarcinoma Caco-2 cell line"',
        '"Crizotinib are selected to test their cytotoxic effects on human epithelial colorectal adenocarcinoma Caco-2 cell line"',
        'The results indicate that crizotinib exhibits moderate cytotoxicity against CRC Caco-2 cells'],
       ['A review article on clinical findings and methods for detecting ROS1 in clinical laboratories. Colorectal carcinoma is mentioned once in the list of tumors where ROS1 rearrangements can occur',
        '"crizotinib has been shown to be an effective inhibitor of ROS1 and has received Food and Drug Administration approval for treatment of advanced NSCLC"',
        'Therapeutic efficacy cannot be assessed for CRC'],

### back

In [ ]:
dfo = pd.read_csv('new_criteria_ana_en2.csv')
dfo['PMID'] = dfo['PMID'].astype(str)
dfo[['s1','s2','s3']] = dfo[['s1','s2','s3']].astype(int)
dfo.head(2)

,PMID,s1,s2,s3,r1,r2,r3,accept
0,34766064,-1,-1,-1,The article describes the clinical case of a 1...,Crizotinib has been used to treat mesothelioma,The effectiveness of crizotinib for CRC has no...,False
1,32208873,1,-1,-1,"""16 colorectal cancer cases""",The abstract states that patients received inh...,The abstract provides general data for the coh...,False

In [ ]:
from sklearn.model_selection import train_test_split

X = dfo.iloc[:,:1]
y = dfo.iloc[:,]
# stratify by accept/not accept. maybe instead by [1,1,0]?
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, 
                                                    random_state=42,stratify=dfo.accept)

In [ ]:
df_p_e = main.run_screening(pmid_list=X_train.PMID.values, 
                            fin_condition='Colorectal cancer', 
                            treatment='Crizotinib',
                            ps_thresh = [1,1,0], real=False)
df_p_e.to_csv('screening.csv',index=False)

INFO:root:COLLECTING PAPER TEXTS
INFO:root:1.0490188598632812
INFO:root:SCREENING PAPERS
INFO:root:0.008991241455078125

In [ ]:
df_p_e.head(2)

,PMID,s1,s2,s3,r1,r2,r3,Fin_text
0,34898475,1,1,0,The study explicitly focuses on 'colorectal ca...,The results section explicitly mentions 'S-cri...,The study identifies Crizotinib via 'in silico...,Identification of a novel immune signature for...
1,28320945,1,1,1,The study explicitly uses a 'human colorectal ...,The text states: 'Addition of the dual MET/RON...,The study evaluates therapeutic effectiveness ...,Three-dimensional culture system identifies a ...

In [ ]:
y_train.head(2)

,PMID,s1,s2,s3,r1,r2,r3,accept
41,34898475,1,-1,-1,"""expression profiles and clinical characterist...",The drug is mathematically predicted to be pot...,Therapeutic efficacy has not been assessed,False
8,28320945,1,1,1,"""human colorectal cancer (CRC) cell line (HCA-...","""Addition of the dual MET/RON tyrosine kinase ...",Evaluates the therapeutic efficacy of crizotin...,True

In [ ]:
df_p_e = pd.read_csv('screening.csv')
errors_df, correct_df = main.find_mistakes(df_p_e, y_train)
print(errors_df.shape)
errors_df.head(3)

(33, 7)

,PMID,num,Fin_text,s_pred,r_pred,s_expert,r_expert
3,22845480,1,Personalized medicine and pharmacogenetic biom...,1,The text explicitly mentions 'KRAS against the...,-1,"CRC is mentioned once in the list, but only in..."
12,23585220,1,Symptomatic reduction in free testosterone lev...,0,The provided text mentions 'male cancer patien...,-1,"The study includes men with cancer, but there ..."
13,23585220,2,Symptomatic reduction in free testosterone lev...,0,"While the study investigates 'Crizotinib', the...",-1,The drug is not being studied specifically for...

In [ ]:
#error_id_df = main.find_ind_errors(errors_df=errors_df,
                            fin_condition='Colorectal cancer', 
                            treatment='Crizotinib')
print(error_id_df.shape)
error_id_df.to_csv('outputs/error_id_df.csv', index=False)
error_id_df.head(2)

INFO:root:22845480, 1, The text explicitly mentions 'KRAS against the use of cetuximab and panitumumab in colorectal cancer', confirming that colorectal cancer is a studied disease/condition in the context of the biomarkers
INFO:root:23585220, 1, The provided text mentions 'male cancer patients' but does not specify the type of cancer (e.g., colorectal, lung, etc.). Therefore, it is uncertain if the study includes patients with colorectal canc
INFO:root:23585220, 2, While the study investigates 'Crizotinib', the text does not specify the underlying cancer type for which the patients were being treated. Without confirmation that the patients have colorectal cancer
INFO:root:23585220, 3, The study evaluates symptomatic reduction in testosterone levels and hypogonadal effects, not the therapeutic effectiveness or antitumor activity of Crizotinib against the cancer itself. Furthermore,
INFO:root:23719267, 3, The text discusses the promise of crizotinib in NSCLC but does not provide specific efficacy outcomes or therapeutic effectiveness data for crizotinib in colorectal cancer.
INFO:root:23719267, 2, The text mentions crizotinib as a therapy for NSCLC with ROS1 fusions but does not explicitly state that crizotinib was investigated or tested specifically in colorectal cancer models or patients with
INFO:root:23719267, 1, The text explicitly lists 'colorectal cancer' as one of the human cancers where ROS1 undergoes genetic rearrangements, confirming the disease is represented in the scope of the review.
INFO:root:25139705, 1, The text explicitly lists 'colorectal cancer' as one of the solid tumors under investigation and mentions approved agents for it, confirming the disease is represented in the study's scope.
INFO:root:26468446, 1, The text explicitly lists 'colorectal cancer' among the types of cancer where aberrant forms of ALK are involved in pathogenesis, satisfying the criterion for the disease/condition being represented.
INFO:root:26995877, 1, The text explicitly mentions 'colorectal cancer' in the context of companion diagnostics, stating: 'KRAS against the use of cetuximab and panitumumab in colorectal cancer'. This confirms the disease c
INFO:root:28183697, 1, The text explicitly states that 'Responses were observed in... colorectal cancer', confirming that patients with colorectal cancer were included in the study cohort.
INFO:root:29466887, 1, The study explicitly lists 'colorectal' cancer as one of the conditions reviewed regarding quality of care and reimbursement schemes, stating: 'Quality of breast, colorectal, lung, head & neck, and ga
INFO:root:34898475, 2, The results section explicitly mentions 'S-crizotinib' (a semantic equivalent of Crizotinib) as an agent identified through in silico therapeutics screening that 'might have potential therapeutic impl
INFO:root:34898475, 3, The study identifies Crizotinib via 'in silico therapeutics screening' and suggests it 'might have potential therapeutic implications', but it does not provide data on actual therapeutic effectiveness
INFO:root:35343863, 3, The provided content is an abstract of a patent review summarizing inhibitors undergoing clinical trials and patented advances. It does not provide specific data, results, or evaluations of the therap
INFO:root:35343863, 2, The text mentions that 'only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC' and discusses the need for new inhibitors due to resistance. It does not explicitly state that t
INFO:root:35343863, 1, The introduction explicitly states that ROS1 is involved in the formation of 'colorectal cancer' among other malignant tumors, indicating the disease is a subject of the review's scope.
INFO:root:36129915, 2, The Results section explicitly lists 'crizotinib' among the 'putative therapeutic candidates' selected based on drug-target network analysis for P:R fusion-positive CRC, confirming it is investigated
INFO:root:36627781, 3, The text describes the review as covering 'ALK signaling, their inhibitors and related structure activity relationships' but does not provide specific data or conclusions regarding the therapeutic eff
INFO:root:36627781, 1, The text explicitly lists 'colorectal cancer' as one of the human cancers where ALK plays a role in pathogenesis, confirming the disease is represented in the scope of the review.
INFO:root:36627781, 2, The text mentions Crizotinib as a first-generation ALK inhibitor used for ALK-dependent NSCLC and discusses the need for novel inhibitors to overcome resistance, but it does not explicitly state that
INFO:root:36801912, 2, The text confirms that 'crizotinib' was investigated as part of combination regimens with vemurafenib. However, because it is uncertain whether the study population included patients with colorectal c
INFO:root:36801912, 3, The text reports efficacy outcomes (OS, PFS, ORR) for the combination regimens including crizotinib. However, since the inclusion of colorectal cancer patients is uncertain, it is uncertain if these e
INFO:root:37686423, 1, The text explicitly states that the review highlights the current landscape of targeted therapy in 'colorectal cancer', confirming that this disease is a studied condition.
INFO:root:37773318, 3, The text evaluates the therapeutic effectiveness by describing 'ALK inhibitor activity' and noting that 'each of the approved ALK inhibitors have shown activity' in the listed cancers, including color
INFO:root:37773318, 1, The text explicitly lists 'colorectal' cancer among the solid tumors where ALK inhibitor activity has been reported, stating: 'Moreover, there are numerous reports of ALK inhibitor activity in multipl
INFO:root:37773318, 2, The text identifies Crizotinib as one of the primary agents studied in these contexts, stating: 'Many reports used crizotinib or alectinib, but each of the approved ALK inhibitors have shown activity.
INFO:root:38378070, 2, The text mentions that 'PharmacoGx data indicated that the expression level of SDHB was correlated with drug sensitivity to Crizotinib', confirming that Crizotinib is investigated as an experimental f
INFO:root:40140597, 1, The study explicitly mentions 'RASMT colorectal cancer (CRC)' in the Background and states that the combination was further explored in 'RASMT CRC patients' in the Conclusions, confirming the inclusio
INFO:root:40140597, 2, The Methods section states that patients received 'PD-0325901 with crizotinib', and the Conclusions confirm the dosing of 'PD-0325901/crizotinib', indicating that Crizotinib was investigated as an int
INFO:root:40140597, 3, The Results section reports 'The best clinical response was stable disease in seven patients (29%)', which is a clinically relevant efficacy outcome evaluating the antitumor activity of the interventi
INFO:root:41213063, 2, The text explicitly mentions 'Crizotinib' in the context of drug sensitivity analysis, stating that 'drugs such as FTI-277, DMOG, and Crizotinib were more sensitive to low-risk group', indicating it w
INFO:root:41213063, 3, The study reports computational drug sensitivity predictions ('more sensitive to low-risk group') but does not provide data on actual therapeutic effectiveness, antitumor activity, or clinically/biolo
INFO:root: passing 33 queries to llama.cpp...

http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf

INFO:root:fresh response in asynch: reasoning='The model incorrectly interpreted the mention of colorectal cancer as a responder subgroup as sufficient evidence for inclusion. The expert correctly identified that while CRC patients were present, the study lacked specific focus, detailed analysis, or dedicated models for CRC, making the inclusion status uncertain rather than confirmed.' error="The model erroneously classified the study as including CRC patients based solely on a list of responder types, ignoring the expert's point that CRC was not a focused cohort with specific analysis or models, rendering the inclusion uncertain."
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly interpreted the mention of colorectal cancer as evidence that the disease itself was the subject of the study. The abstract is a review of pharmacogenetic biomarkers across various cancers. Colorectal cancer is merely cited as an example context for the KRAS biomarker, not as the primary focus of investigation. The study investigates biomarkers, not the disease pathology or treatment outcomes specifically for CRC.' error="The model failed to distinguish between the study's primary subject (biomarkers) and the diseases listed as examples. It incorrectly assumed that mentioning CRC in a list of biomarker applications meant CRC was the studied condition, ignoring that the paper reviews biomarkers generally."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model assigned a score of 0 (UNCERTAIN) because the cancer type was unspecified. However, the expert assigned -1 (NO) because the absence of any mention of Colorectal Cancer (CRC) in the abstract explicitly confirms the criterion is not met. The model failed to recognize that missing specific disease information in the context of a general 'cancer' study constitutes a definitive exclusion for a disease-specific criterion, rather than uncertainty." error='The model incorrectly scored UNCERTAIN (0) instead of NO (-1). It failed to recognize that the complete absence of any mention of Colorectal Cancer in the abstract definitively excludes the study, rather than leaving the status ambiguous.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model scored 0 (Uncertain) because it noted the lack of explicit mention of Crizotinib in Colorectal Cancer. However, the expert scored -1 (No) because the text explicitly links Crizotinib only to NSCLC. Since the study is a review discussing ROS1 fusions generally but citing Crizotinib's efficacy specifically in NSCLC, and does not present data or investigation of Crizotinib for Colorectal Cancer, the criterion is not met. The model failed to recognize that the specific association with NSCLC excludes it from being an intervention for Colorectal Cancer in this context, leading to an uncertain rather than negative classification." error='The model incorrectly classified the score as Uncertain (0) instead of No (-1). It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning Colorectal Cancer only as a site of ROS1 fusions without linking it to Crizotinib, constitutes a definitive negative for the specific intervention-disease pair.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The expert correctly identifies that the study focuses on endocrine side effects, not antitumor activity, leading to a definitive 'NO' (-1). The model incorrectly assigned 'UNCERTAIN' (0), likely due to the unspecified cancer type, but failed to recognize that the primary outcome (testosterone levels) is irrelevant to the criterion of antitumor efficacy regardless of cancer type." error="The model incorrectly scored UNCERTAIN because the cancer type was unspecified, failing to recognize that the study's focus on endocrine side effects definitively excludes it from evaluating antitumor activity, which warrants a NO score."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model scored 0 (Uncertain) because it could not confirm the cancer type. However, the abstract explicitly states the study population is 'male cancer patients' treated with Crizotinib, without specifying Colorectal Cancer (CRC). Since the study does not investigate Crizotinib for CRC, the criterion is not met. The correct score is -1 (No), as the study focuses on a side effect (hypogonadism) in a general cancer population, not CRC treatment efficacy or safety." error="The model incorrectly assigned 'Uncertain' (0) due to missing cancer type information, failing to recognize that the absence of 'Colorectal Cancer' in the study population explicitly means the criterion is not met, warranting a 'No' (-1) score."
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly classified the study as including colorectal cancer patients/samples because it was listed in the background. However, the study focuses on ALK-rearranged cancers generally, with specific clinical data and drug approvals (Crizotinib, Ceritinib) cited only for NSCLC. There is no evidence of CRC patients, models, or samples being studied.' error='The model mistook a background mention of colorectal cancer in a list of ALK-associated diseases for actual study inclusion, ignoring that the research focuses on NSCLC and general mechanisms without specific CRC data.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model scored 0 (Uncertain) because it noted the lack of specific data for colorectal cancer. However, the expert correctly identified that the text explicitly restricts Crizotinib's approved use and discussed effectiveness to NSCLC. Since the text confirms Crizotinib is for NSCLC and does not claim efficacy for colorectal cancer, the criterion is explicitly not met (-1), not just missing information." error="The model failed to recognize that explicitly limiting Crizotinib's efficacy to NSCLC constitutes a definitive exclusion for colorectal cancer, incorrectly labeling it as uncertain instead of a clear negative."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model scored 0 (Uncertain) because it viewed the in silico prediction as insufficient for a definitive 'Yes' but not explicitly negative. The expert scored -1 (No) because the study explicitly did not evaluate therapeutic effectiveness; it only performed computational screening. The absence of efficacy evaluation is a definitive negative fact, not an uncertainty." error="The model incorrectly classified the absence of efficacy evaluation as 'Uncertain' (0) instead of 'No' (-1). Since the study only performed in silico screening and explicitly did not assess therapeutic effectiveness, the criterion is definitively not met."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The study is a bioinformatics analysis identifying putative drug candidates via network analysis, not an experimental investigation of Crizotinib's efficacy or mechanism in Colorectal Cancer. The model incorrectly equated computational prediction with actual investigation of the intervention." error='The model confused computational prediction of drug candidates with actual experimental investigation of the intervention, failing to recognize that bioinformatics inference does not constitute investigating the drug as a treatment.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly interpreted the mention of colorectal cancer in a policy analysis as meeting the criterion for including patients or biological samples. The expert correctly identified that the study is a health economics review of reimbursement schemes, not a clinical or biological study involving actual patients, animal models, organoids, cell lines, or biological samples. The criterion requires the study to include these entities as subjects, which this policy analysis does not do.' error='The model failed to distinguish between a policy/economic analysis mentioning a disease and a study that actually includes patients or biological samples as subjects. It incorrectly scored YES because CRC was mentioned, ignoring the requirement for direct inclusion of patients/samples.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly interpreted the mention of colorectal cancer in a review article as evidence of original study inclusion. The expert correctly identified that the abstract describes a review of existing literature and approved agents, not a primary study involving new patients, animal models, organoids, cell lines, or biological samples.' error="The model failed to distinguish between a review article summarizing existing treatments and a primary study involving original subjects. It incorrectly assumed that mentioning colorectal cancer as a condition treated by approved agents constituted 'including' patients or samples in the study."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model incorrectly assumed that the general statement of ALK inhibitor activity in colorectal cancer constituted an evaluation of Crizotinib's effectiveness for that specific indication. The expert correctly identified that the specific efficacy data (response rates) cited in the abstract applies only to approved indications (NSCLC, IMT, ALCL), not colorectal cancer, where only general activity is mentioned without specific efficacy outcomes for Crizotinib." error='The model conflated general mentions of activity in colorectal cancer with specific efficacy evaluation, ignoring that the cited response rates applied only to other approved indications, not CRC.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly classified a review article as including primary study subjects. The expert correctly identified that the text is a review of existing literature and FDA-approved drugs, not a primary study involving patients, animal models, or biological samples of colorectal cancer.' error='The model failed to distinguish between a review article discussing a disease and a primary study involving actual patients or biological samples of that disease, incorrectly assuming mention implies inclusion of study subjects.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The abstract is a review discussing ROS1 fusions broadly across multiple cancer types. While colorectal cancer is listed as one of the cancers where ROS1 rearrangements occur, the study does not specifically investigate or include patients/samples representing colorectal cancer as a primary subject. The expert correctly identifies that mere mention in a list of associated diseases does not constitute the study including CRC as a studied condition, whereas the model incorrectly equated listing the disease with studying it.' error='The model incorrectly assumed that listing colorectal cancer among various cancers with ROS1 rearrangements meant the study specifically included CRC patients or samples, failing to recognize it was just a general review of ROS1 across multiple cancer types.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model incorrectly assumed that reporting efficacy outcomes for the entire cohort of 'advanced solid cancers' satisfies the criterion for 'Colorectal cancer'. The expert correctly identified that the study did not provide efficacy data specifically for colorectal cancer patients, as the results were aggregated for all tumor types without stratification." error='The model failed to recognize that the efficacy outcomes were reported for the entire cohort of advanced solid tumors, not specifically for colorectal cancer patients, thus missing the lack of disease-specific data.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly interpreted a background mention of colorectal cancer as evidence that the study investigates it. The abstract focuses exclusively on ROS1 inhibitors for NSCLC, listing CRC only as a minor example of ROS1 involvement in the introduction, not as a subject of the review.' error="The model mistakenly treated a background list of diseases associated with ROS1 as the study's focus, ignoring that the review exclusively covers NSCLC and excludes CRC from its scope."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The study is an in silico screening identifying potential agents, not an investigation of Crizotinib's efficacy. The expert correctly identifies this as a prediction, not an investigation of the drug as an intervention." error='The model incorrectly classified an in silico prediction of potential efficacy as an investigation of the drug as an intervention, ignoring that no actual treatment study was conducted.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The abstract explicitly states that combined BRAF + MEK inhibition is FDA approved for BRAF V600E-mutant solid tumors 'except for colorectal cancer.' This exclusion implies that colorectal cancer is not the target population for the interventions discussed, including crizotinib combinations. The model failed to interpret this exclusion as a definitive negative for the specific criterion of investigating crizotinib for colorectal cancer, instead marking it as uncertain." error='The model failed to recognize that the explicit exclusion of colorectal cancer from the approved indications for the studied regimen implies crizotinib is not being investigated for this specific cancer type, leading to an incorrect UNCERTAIN score instead of NO.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The abstract is a review discussing ROS1 fusions generally. It mentions colorectal cancer only as a cancer type where ROS1 fusions occur, not as a subject of efficacy evaluation. It explicitly states crizotinib's promise is in NSCLC. Therefore, the study does not evaluate crizotinib for colorectal cancer, making the answer definitively NO (-1), not UNCERTAIN (0)." error="The model incorrectly assigned UNCERTAIN (0) instead of NO (-1). It failed to recognize that mentioning a disease in a list of affected cancers without evaluating the drug's efficacy for that specific disease constitutes a definitive exclusion, not ambiguity."
INFO:root:
INFO:root:fresh response in asynch: reasoning='The abstract is a review discussing companion diagnostics broadly. Colorectal cancer is cited merely as an illustrative example of a disease area where CoDx are applied, not as the specific subject of investigation or study population. The expert correctly identifies this as an example, leading to exclusion, whereas the model incorrectly treated the mention as confirmation of inclusion.' error="The model incorrectly classified a background example of colorectal cancer as the study's focus, failing to recognize that the abstract is a general review where CRC is only cited illustratively."
INFO:root:
INFO:root:fresh response in asynch: reasoning='The model incorrectly classified the study as including colorectal cancer patients because it was listed among examples of tumors with reported ALK inhibitor activity. However, the abstract describes a review focusing on ALK alterations beyond NSCLC, and colorectal cancer is merely cited as background evidence of pan-cancer activity, not as a primary subject of new investigation or data collection.' error='The model mistook a background citation of colorectal cancer in a list of examples for primary study inclusion, failing to recognize that the study is a review where CRC is not the main focus.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model scored 0 (Uncertain) because it felt the abstract didn't explicitly confirm if Crizotinib data for CRC was included. However, the expert scored -1 (No) because the abstract explicitly links Crizotinib only to NSCLC treatment. Since the study is a review of ROS1 inhibitors and Crizotinib is only discussed regarding NSCLC, it is not investigated as an intervention for Colorectal Cancer. The model failed to recognize that the explicit association with a different cancer type (NSCLC) constitutes a definitive 'No' for the specific criterion (CRC), rather than an uncertainty." error="The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning CRC only as a background condition for ROS1 involvement, definitively excludes Crizotinib as an intervention for CRC in this study."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The expert correctly identifies that the study explicitly excludes colorectal cancer from its scope, as stated in the abstract ('except for colorectal cancer'). Therefore, the study does not evaluate Crizotinib for Colorectal Cancer, warranting a score of -1. The model incorrectly assigned a score of 0 (Uncertain), likely due to a failure to recognize the explicit exclusion clause or misinterpreting the general 'solid tumors' mention as potentially including colorectal cancer despite the specific exception." error='The model failed to recognize the explicit exclusion of colorectal cancer in the abstract, incorrectly labeling the eligibility as uncertain instead of definitively negative.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model correctly identified Crizotinib as an intervention but failed to verify the patient population. The abstract specifies 'advanced solid tumours' generally, not specifically Colorectal Cancer (CRC). While CRC is mentioned in the background and future plans, the actual study population was mixed solid tumors, meaning the criterion for investigating Crizotinib specifically for CRC was not met." error="The model ignored the patient population constraint. It confirmed Crizotinib was used but failed to notice the study enrolled patients with 'advanced solid tumours' generally, not specifically Colorectal Cancer, despite CRC being mentioned only in background/future context."
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model incorrectly assumed that mentioning CRC in the background and future exploration plans meant the current study included CRC patients. The expert correctly identified that the actual study population was 'advanced solid tumors' generally, with no specific inclusion of CRC patients in this phase Ia trial." error='The model conflated background context and future plans with the actual study population, ignoring that the trial enrolled patients with advanced solid tumors generally, not specifically colorectal cancer.'
INFO:root:
INFO:root:fresh response in asynch: reasoning='The abstract explicitly states Crizotinib is used for NSCLC. While colorectal cancer is listed as a condition involving ALK, the study focuses on developing novel inhibitors, not investigating Crizotinib for colorectal cancer. The model incorrectly marked this as uncertain instead of a definitive no.' error='The model failed to recognize that mentioning Crizotinib for NSCLC explicitly excludes it as an intervention for colorectal cancer in this context, leading to an incorrect UNCERTAIN score instead of NO.'
INFO:root:
INFO:root:fresh response in asynch: reasoning="The model incorrectly interpreted a background mention of colorectal cancer in a list of diseases affected by ALK as evidence that the study investigates CRC. The expert correctly identified that CRC is merely listed as context for ALK's role, while the study's actual focus is on ALK inhibitors for NSCLC and general drug design, not CRC-specific research." error='The model mistakenly treated a background mention of colorectal cancer in a list of ALK-associated diseases as evidence that the study investigates CRC, ignoring that the review focuses on ALK inhibitors generally and NSCLC specifically.'
INFO:root:

(33, 9)

,PMID,num,Fin_text,s_pred,r_pred,s_expert,r_expert,error_id_reason,error_id
3,22845480,1,Personalized medicine and pharmacogenetic biom...,1,The text explicitly mentions 'KRAS against the...,-1,"CRC is mentioned once in the list, but only in...",The model incorrectly interpreted the mention ...,The model failed to distinguish between the st...
12,23585220,1,Symptomatic reduction in free testosterone lev...,0,The provided text mentions 'male cancer patien...,-1,"The study includes men with cancer, but there ...",The model assigned a score of 0 (UNCERTAIN) be...,The model incorrectly scored UNCERTAIN (0) ins...

In [ ]:
# TO COMPARE WITH EXPERT
q = error_id_df[['PMID','num','error_id']]


df1 = pd.read_csv('common_errors_fixed.csv')
for i in ['PMID_статьи','Номер_критерия','Оценка_ЛЛМ','Оценка_Эксперт']:
    if i =='PMID_статьи':
        df1[i] = df1[i].apply(lambda x: str(int(x)))
    else:
        df1[i] = df1[i].apply(lambda x: int(x))
df1 = df1[['PMID_статьи','Номер_критерия',
    'Почему_ошибка','Тип_ошибки']]
print(df1.shape)
df1.head(2)

NameError: name 'error_id_df' is not defined

In [ ]:
merged = pd.merge(q,df1,left_on=['PMID','num'],right_on=['PMID_статьи','Номер_критерия'],
        how='left')
print(merged.shape)
merged.drop(columns=['PMID_статьи','Номер_критерия']).values

ValueError: You are trying to merge on int64 and object columns for key 'PMID'. If you wish to proceed you should use pd.concat

In [ ]:
fin_condition='Colorectal cancer'
treatment='Crizotinib'

In [ ]:
fin_condition='Colorectal cancer'
treatment='Crizotinib'
error_id_df = pd.read_csv('outputs/error_id_df.csv')
error_type_df, outs = main.find_error_clusters(error_id_df,
                                                fin_condition, treatment)
print(error_type_df.shape)

error_type_df.to_csv('outputs/error_type_df.csv')
error_type_df.head(2)

INFO:root: passing 1 queries to llama.cpp...

    eligibility_criteria = ["Does the study include patients, animal models, organoids, cell lines, or biological samples representing 'Colorectal cancer' as a studied disease/condition?", "Does the study investigate 'Crizotinib' as an intervention, treatment, exposure, or experimental factor for 'Colorectal cancer'?", "Does the study evaluate the therapeutic effectiveness or antitumor activity of 'Crizotinib' for 'Colorectal cancer' using clinically or biologically relevant efficacy outcomes?"]
    model_errors = error_index | criteria_num | error_description
0 | 1 | The model failed to distinguish between the study's primary subject (biomarkers) and the diseases listed as examples. It incorrectly assumed that mentioning CRC in a list of biomarker applications meant CRC was the studied condition, ignoring that the paper reviews biomarkers generally.
1 | 1 | The model incorrectly scored UNCERTAIN (0) instead of NO (-1). It failed to recognize that the complete absence of any mention of Colorectal Cancer in the abstract definitively excludes the study, rather than leaving the status ambiguous.
2 | 2 | The model incorrectly assigned 'Uncertain' (0) due to missing cancer type information, failing to recognize that the absence of 'Colorectal Cancer' in the study population explicitly means the criterion is not met, warranting a 'No' (-1) score.
3 | 3 | The model incorrectly scored UNCERTAIN because the cancer type was unspecified, failing to recognize that the study's focus on endocrine side effects definitively excludes it from evaluating antitumor activity, which warrants a NO score.
4 | 3 | The model incorrectly assigned UNCERTAIN (0) instead of NO (-1). It failed to recognize that mentioning a disease in a list of affected cancers without evaluating the drug's efficacy for that specific disease constitutes a definitive exclusion, not ambiguity.
5 | 2 | The model incorrectly classified the score as Uncertain (0) instead of No (-1). It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning Colorectal Cancer only as a site of ROS1 fusions without linking it to Crizotinib, constitutes a definitive negative for the specific intervention-disease pair.
6 | 1 | The model incorrectly assumed that listing colorectal cancer among various cancers with ROS1 rearrangements meant the study specifically included CRC patients or samples, failing to recognize it was just a general review of ROS1 across multiple cancer types.
7 | 1 | The model failed to distinguish between a review article summarizing existing treatments and a primary study involving original subjects. It incorrectly assumed that mentioning colorectal cancer as a condition treated by approved agents constituted 'including' patients or samples in the study.
8 | 1 | The model mistook a background mention of colorectal cancer in a list of ALK-associated diseases for actual study inclusion, ignoring that the research focuses on NSCLC and general mechanisms without specific CRC data.
9 | 1 | The model incorrectly classified a background example of colorectal cancer as the study's focus, failing to recognize that the abstract is a general review where CRC is only cited illustratively.
10 | 1 | The model erroneously classified the study as including CRC patients based solely on a list of responder types, ignoring the expert's point that CRC was not a focused cohort with specific analysis or models, rendering the inclusion uncertain.
11 | 1 | The model failed to distinguish between a policy/economic analysis mentioning a disease and a study that actually includes patients or biological samples as subjects. It incorrectly scored YES because CRC was mentioned, ignoring the requirement for direct inclusion of patients/samples.
12 | 2 | The model incorrectly classified an in silico prediction of potential efficacy as an investigation of the drug as an intervention, ignoring that no actual treatment study was conducted.
13 | 3 | The model incorrectly classified the absence of efficacy evaluation as 'Uncertain' (0) instead of 'No' (-1). Since the study only performed in silico screening and explicitly did not assess therapeutic effectiveness, the criterion is definitively not met.
14 | 3 | The model failed to recognize that explicitly limiting Crizotinib's efficacy to NSCLC constitutes a definitive exclusion for colorectal cancer, incorrectly labeling it as uncertain instead of a clear negative.
15 | 2 | The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning CRC only as a background condition for ROS1 involvement, definitively excludes Crizotinib as an intervention for CRC in this study.
16 | 1 | The model mistakenly treated a background list of diseases associated with ROS1 as the study's focus, ignoring that the review exclusively covers NSCLC and excludes CRC from its scope.
17 | 2 | The model confused computational prediction of drug candidates with actual experimental investigation of the intervention, failing to recognize that bioinformatics inference does not constitute investigating the drug as a treatment.
18 | 3 | The model failed to recognize that mentioning CRC as a disease involving ALK does not imply evaluating Crizotinib's efficacy for it. The study focuses on ALK inhibitors for ALK-dependent cancers like NSCLC, so efficacy for CRC is explicitly not assessed, requiring a -1, not 0.
19 | 1 | The model mistakenly treated a background mention of colorectal cancer in a list of ALK-associated diseases as evidence that the study investigates CRC, ignoring that the review focuses on ALK inhibitors generally and NSCLC specifically.
20 | 2 | The model failed to recognize that mentioning Crizotinib for NSCLC explicitly excludes it as an intervention for colorectal cancer in this context, leading to an incorrect UNCERTAIN score instead of NO.
21 | 2 | The model failed to recognize that the explicit exclusion of colorectal cancer from the approved indications for the studied regimen implies crizotinib is not being investigated for this specific cancer type, leading to an incorrect UNCERTAIN score instead of NO.
22 | 3 | The model failed to recognize the explicit exclusion of colorectal cancer in the abstract, incorrectly labeling the eligibility as uncertain instead of definitively negative.
23 | 1 | The model failed to distinguish between a review article discussing a disease and a primary study involving actual patients or biological samples of that disease, incorrectly assuming mention implies inclusion of study subjects.
24 | 3 | The model conflated general mentions of activity in colorectal cancer with specific efficacy evaluation, ignoring that the cited response rates applied only to other approved indications, not CRC.
25 | 1 | The model mistook a background citation of colorectal cancer in a list of examples for primary study inclusion, failing to recognize that the study is a review where CRC is not the main focus.
26 | 2 | The model erroneously equated the general mention of Crizotinib and CRC in a broad review with a specific investigation of Crizotinib for CRC, ignoring the lack of focused data or primary intent.
27 | 2 | The model incorrectly classified a computational drug sensitivity correlation from a database as an experimental investigation of Crizotinib as an intervention, ignoring that the study focuses on biomarker identification, not drug testing.
28 | 1 | The model conflated background context and future plans with the actual study population, ignoring that the trial enrolled patients with advanced solid tumors generally, not specifically colorectal cancer.
29 | 2 | The model ignored the patient population constraint. It confirmed Crizotinib was used but failed to notice the study enrolled patients with 'advanced solid tumours' generally, not specifically Colorectal Cancer, despite CRC being mentioned only in background/future context.
30 | 3 | The model failed to recognize that the efficacy outcomes were reported for the entire cohort of advanced solid tumors, not specifically for colorectal cancer patients, thus missing the lack of disease-specific data.
31 | 2 | The model incorrectly classified computational drug sensitivity prediction as an experimental investigation of the drug as an intervention, failing to distinguish between in silico modeling and actual clinical or experimental treatment.
32 | 3 | The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that reporting only computational drug sensitivity predictions, without any actual therapeutic effectiveness or antitumor activity data, definitively fails the criterion, warranting a 'No' score.

    your_response =

http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf

INFO:root:fresh response in asynch: reasoning="The errors can be clustered into four distinct root causes based on the cognitive mechanism of the failure:\n1. **Confusing Background/Example Mentions with Study Focus**: The model incorrectly interprets a disease mentioned in a list, background, or as an example as the primary subject of the study. This applies to Criteria 1 and 2.\n2. **Misinterpreting Study Design/Methodology**: The model fails to distinguish between primary studies (patients/samples) and reviews/policy analyses, or between experimental/clinical investigations and in silico/computational predictions. This applies to Criteria 1 and 2.\n3. **Treating Explicit Exclusion or Absence as Ambiguity**: The model assigns 'Uncertain' when the text explicitly excludes the condition, limits the scope to another disease, or completely lacks the required information, which should result in a 'No'. This applies to Criteria 1, 2, and 3.\n4. **Ignoring Population Specificity in Efficacy Evaluation**: The model fails to recognize that if" clusters=[Cluster(reasoning='The model conflates incidental mentions (lists, background, examples) with the primary study focus or inclusion.', index=0, name='Confusing background/example mentions with study focus', notable_pointers=['CRC listed as example of biomarker application', 'CRC mentioned in list of ROS1/ALK associated diseases', 'CRC cited illustratively in general review', 'Background mention mistaken for primary inclusion']), Cluster(reasoning='The model fails to distinguish between primary studies (patients/samples) and secondary studies (reviews/policy), or between experimental interventions and computational predictions.', index=1, name='Misinterpreting study design or methodology type', notable_pointers=['Review article mistaken for primary study with patients', 'Policy/economic analysis mistaken for patient inclusion', 'In silico prediction mistaken for experimental intervention', 'Computational screening mistaken for efficacy evaluation']), Cluster(reasoning="The model assigns 'Uncertain' instead of 'No' when the study explicitly excludes the condition, limits scope to another disease, or lacks the required information entirely.", index=2, name='Treating explicit exclusion or absence as ambiguity', notable_pointers=['Complete absence of CRC mention treated as uncertain', 'Explicit focus on NSCLC treated as uncertain for CRC', 'Explicit exclusion of CRC from indications treated as uncertain', 'Unspecified cancer type treated as uncertain instead of no']), Cluster(reasoning='The model fails to recognize that efficacy outcomes reported for a broad cohort (e.g., solid tumors) do not constitute specific efficacy data for the target disease (CRC).', index=3, name='Ignoring population specificity in efficacy evaluation', notable_pointers=['Efficacy reported for advanced solid tumors, not CRC', 'Response rates applied to other indications, not CRC', 'Lack of disease-specific data in broad cohort'])] errors=[Error(reasoning='Model confused a list of biomarker applications with the study focus.', error_index=0, cluster_index=0), Error(reasoning='Model treated complete absence of mention as ambiguous rather than definitive exclusion.', error_index=1, cluster_index=2), Error(reasoning='Model treated unspecified cancer type (absence of CRC) as ambiguous rather than definitive exclusion', error_index=2, cluster_index=2), Error(reasoning='Model treated explicit focus on side effects (excluding efficacy) as ambiguous.', error_index=3, cluster_index=2), Error(reasoning='Model treated mention in a list without efficacy evaluation as ambiguous.', error_index=4, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background mention of CRC as ambiguous.', error_index=5, cluster_index=2), Error(reasoning='Model confused a list of cancers with ROS1 rearrangements with specific inclusion of CRC patients.', error_index=6, cluster_index=0), Error(reasoning='Model confused a review article with a primary study involving patients.', error_index=7, cluster_index=1), Error(reasoning='Model confused a background mention in a list with actual study inclusion.', error_index=8, cluster_index=0), Error(reasoning='Model confused a background example with the study focus.', error_index=9, cluster_index=0), Error(reasoning='Model confused a list of responder types with a focused cohort.', error_index=10, cluster_index=0), Error(reasoning='Model confused a policy analysis with a study including patients.', error_index=11, cluster_index=1), Error(reasoning='Model confused in silico prediction with actual experimental investigation.', error_index=12, cluster_index=1), Error(reasoning='Model treated absence of efficacy evaluation (in silico only) as ambiguous.', error_index=13, cluster_index=2), Error(reasoning='Model treated explicit limitation to NSCLC as ambiguous for CRC.', error_index=14, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background CRC as ambiguous.', error_index=15, cluster_index=2), Error(reasoning='Model confused a background list of diseases with the study focus.', error_index=16, cluster_index=0), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=17, cluster_index=1), Error(reasoning='Model treated mention of CRC as disease involving ALK as implying efficacy evaluation.', error_index=18, cluster_index=2), Error(reasoning='Model confused a background mention with evidence of investigation.', error_index=19, cluster_index=0), Error(reasoning='Model treated explicit exclusion of CRC from indications as ambiguous.', error_index=20, cluster_index=2), Error(reasoning='Model treated explicit exclusion from approved indications as ambiguous.', error_index=21, cluster_index=2), Error(reasoning='Model treated explicit exclusion in abstract as ambiguous.', error_index=22, cluster_index=2), Error(reasoning='Model confused a review discussing a disease with a primary study involving patients.', error_index=23, cluster_index=1), Error(reasoning='Model failed to recognize efficacy outcomes were not specific to CRC.', error_index=24, cluster_index=3), Error(reasoning='Model confused a background citation with primary study inclusion.', error_index=25, cluster_index=0), Error(reasoning='Model confused general mention in a broad review with specific investigation.', error_index=26, cluster_index=0), Error(reasoning='Model confused computational correlation with experimental investigation.', error_index=27, cluster_index=1), Error(reasoning='Model confused background context/future plans with actual study population.', error_index=28, cluster_index=0), Error(reasoning='Model failed to notice study enrolled general solid tumors, not specifically CRC.', error_index=29, cluster_index=3), Error(reasoning='Model failed to recognize efficacy outcomes were for entire cohort, not specifically CRC.', error_index=30, cluster_index=3), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=31, cluster_index=1), Error(reasoning='Model treated computational predictions (no actual efficacy data) as ambiguous.', error_index=32, cluster_index=2)]
INFO:root:

(33, 11)

,PMID,num,Fin_text,s_pred,r_pred,s_expert,r_expert,error_id_reason,error_id,error_type_reason,error_type
0,22845480,1,Personalized medicine and pharmacogenetic biom...,1,The text explicitly mentions 'KRAS against the...,-1,"CRC is mentioned once in the list, but only in...",The model incorrectly interpreted the mention ...,The model failed to distinguish between the st...,Model confused a list of biomarker application...,Confusing background/example mentions with stu...
1,23585220,1,Symptomatic reduction in free testosterone lev...,0,The provided text mentions 'male cancer patien...,-1,"The study includes men with cancer, but there ...",The model assigned a score of 0 (UNCERTAIN) be...,The model incorrectly scored UNCERTAIN (0) ins...,Model treated complete absence of mention as a...,Treating explicit exclusion or absence as ambi...

In [ ]:
for c in outs.clusters:
    print('\n',c.name)
    print(c.notable_pointers)

 Confusing background/example mentions with study focus
['CRC listed as example of biomarker application', 'CRC mentioned in list of ROS1/ALK associated diseases', 'CRC cited illustratively in general review', 'Background mention mistaken for primary inclusion']

 Misinterpreting study design or methodology type
['Review article mistaken for primary study with patients', 'Policy/economic analysis mistaken for patient inclusion', 'In silico prediction mistaken for experimental intervention', 'Computational screening mistaken for efficacy evaluation']

 Treating explicit exclusion or absence as ambiguity
['Complete absence of CRC mention treated as uncertain', 'Explicit focus on NSCLC treated as uncertain for CRC', 'Explicit exclusion of CRC from indications treated as uncertain', 'Unspecified cancer type treated as uncertain instead of no']

 Ignoring population specificity in efficacy evaluation
['Efficacy reported for advanced solid tumors, not CRC', 'Response rates applied to other indications, not CRC', 'Lack of disease-specific data in broad cohort']

In [ ]:
error_type_df.error_type.value_counts()

error_type
Treating explicit exclusion or absence as ambiguity       13
Confusing background/example mentions with study focus    10
Misinterpreting study design or methodology type           7
Ignoring population specificity in efficacy evaluation     3
Name: count, dtype: int64

In [ ]:
for i in error_type_df.error_type.unique():
    print('\n',i)
    q = error_type_df[error_type_df.error_type==i]
    print(q.error_id.values)
    #error_type_df

 Confusing background/example mentions with study focus
["The model failed to distinguish between the study's primary subject (biomarkers) and the diseases listed as examples. It incorrectly assumed that mentioning CRC in a list of biomarker applications meant CRC was the studied condition, ignoring that the paper reviews biomarkers generally."
 'The model incorrectly assumed that listing colorectal cancer among various cancers with ROS1 rearrangements meant the study specifically included CRC patients or samples, failing to recognize it was just a general review of ROS1 across multiple cancer types.'
 'The model mistook a background mention of colorectal cancer in a list of ALK-associated diseases for actual study inclusion, ignoring that the research focuses on NSCLC and general mechanisms without specific CRC data.'
 "The model incorrectly classified a background example of colorectal cancer as the study's focus, failing to recognize that the abstract is a general review where CRC is only cited illustratively."
 "The model erroneously classified the study as including CRC patients based solely on a list of responder types, ignoring the expert's point that CRC was not a focused cohort with specific analysis or models, rendering the inclusion uncertain."
 "The model mistakenly treated a background list of diseases associated with ROS1 as the study's focus, ignoring that the review exclusively covers NSCLC and excludes CRC from its scope."
 'The model mistakenly treated a background mention of colorectal cancer in a list of ALK-associated diseases as evidence that the study investigates CRC, ignoring that the review focuses on ALK inhibitors generally and NSCLC specifically.'
 'The model mistook a background citation of colorectal cancer in a list of examples for primary study inclusion, failing to recognize that the study is a review where CRC is not the main focus.'
 'The model erroneously equated the general mention of Crizotinib and CRC in a broad review with a specific investigation of Crizotinib for CRC, ignoring the lack of focused data or primary intent.'
 'The model conflated background context and future plans with the actual study population, ignoring that the trial enrolled patients with advanced solid tumors generally, not specifically colorectal cancer.']

 Treating explicit exclusion or absence as ambiguity
['The model incorrectly scored UNCERTAIN (0) instead of NO (-1). It failed to recognize that the complete absence of any mention of Colorectal Cancer in the abstract definitively excludes the study, rather than leaving the status ambiguous.'
 "The model incorrectly assigned 'Uncertain' (0) due to missing cancer type information, failing to recognize that the absence of 'Colorectal Cancer' in the study population explicitly means the criterion is not met, warranting a 'No' (-1) score."
 "The model incorrectly scored UNCERTAIN because the cancer type was unspecified, failing to recognize that the study's focus on endocrine side effects definitively excludes it from evaluating antitumor activity, which warrants a NO score."
 "The model incorrectly assigned UNCERTAIN (0) instead of NO (-1). It failed to recognize that mentioning a disease in a list of affected cancers without evaluating the drug's efficacy for that specific disease constitutes a definitive exclusion, not ambiguity."
 'The model incorrectly classified the score as Uncertain (0) instead of No (-1). It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning Colorectal Cancer only as a site of ROS1 fusions without linking it to Crizotinib, constitutes a definitive negative for the specific intervention-disease pair.'
 "The model incorrectly classified the absence of efficacy evaluation as 'Uncertain' (0) instead of 'No' (-1). Since the study only performed in silico screening and explicitly did not assess therapeutic effectiveness, the criterion is definitively not met."
 "The model failed to recognize that explicitly limiting Crizotinib's efficacy to NSCLC constitutes a definitive exclusion for colorectal cancer, incorrectly labeling it as uncertain instead of a clear negative."
 "The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning CRC only as a background condition for ROS1 involvement, definitively excludes Crizotinib as an intervention for CRC in this study."
 "The model failed to recognize that mentioning CRC as a disease involving ALK does not imply evaluating Crizotinib's efficacy for it. The study focuses on ALK inhibitors for ALK-dependent cancers like NSCLC, so efficacy for CRC is explicitly not assessed, requiring a -1, not 0."
 'The model failed to recognize that mentioning Crizotinib for NSCLC explicitly excludes it as an intervention for colorectal cancer in this context, leading to an incorrect UNCERTAIN score instead of NO.'
 'The model failed to recognize that the explicit exclusion of colorectal cancer from the approved indications for the studied regimen implies crizotinib is not being investigated for this specific cancer type, leading to an incorrect UNCERTAIN score instead of NO.'
 'The model failed to recognize the explicit exclusion of colorectal cancer in the abstract, incorrectly labeling the eligibility as uncertain instead of definitively negative.'
 "The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that reporting only computational drug sensitivity predictions, without any actual therapeutic effectiveness or antitumor activity data, definitively fails the criterion, warranting a 'No' score."]

 Misinterpreting study design or methodology type
["The model failed to distinguish between a review article summarizing existing treatments and a primary study involving original subjects. It incorrectly assumed that mentioning colorectal cancer as a condition treated by approved agents constituted 'including' patients or samples in the study."
 'The model failed to distinguish between a policy/economic analysis mentioning a disease and a study that actually includes patients or biological samples as subjects. It incorrectly scored YES because CRC was mentioned, ignoring the requirement for direct inclusion of patients/samples.'
 'The model incorrectly classified an in silico prediction of potential efficacy as an investigation of the drug as an intervention, ignoring that no actual treatment study was conducted.'
 'The model confused computational prediction of drug candidates with actual experimental investigation of the intervention, failing to recognize that bioinformatics inference does not constitute investigating the drug as a treatment.'
 'The model failed to distinguish between a review article discussing a disease and a primary study involving actual patients or biological samples of that disease, incorrectly assuming mention implies inclusion of study subjects.'
 'The model incorrectly classified a computational drug sensitivity correlation from a database as an experimental investigation of Crizotinib as an intervention, ignoring that the study focuses on biomarker identification, not drug testing.'
 'The model incorrectly classified computational drug sensitivity prediction as an experimental investigation of the drug as an intervention, failing to distinguish between in silico modeling and actual clinical or experimental treatment.']

 Failing to distinguish general cohort data from specific condition data
['The model conflated general mentions of activity in colorectal cancer with specific efficacy evaluation, ignoring that the cited response rates applied only to other approved indications, not CRC.'
 "The model ignored the patient population constraint. It confirmed Crizotinib was used but failed to notice the study enrolled patients with 'advanced solid tumours' generally, not specifically Colorectal Cancer, despite CRC being mentioned only in background/future context."
 'The model failed to recognize that the efficacy outcomes were reported for the entire cohort of advanced solid tumors, not specifically for colorectal cancer patients, thus missing the lack of disease-specific data.']

In [ ]:
error_type_df.PMID = error_type_df.PMID.astype(str)
df1 = pd.read_csv('common_errors_fixed.csv')
for i in ['PMID_статьи','Номер_критерия','Оценка_ЛЛМ','Оценка_Эксперт']:
    if i =='PMID_статьи':
        df1[i] = df1[i].apply(lambda x: str(int(x)))
    else:
        df1[i] = df1[i].apply(lambda x: int(x))
df1 = df1[['PMID_статьи','Номер_критерия',
    'Почему_ошибка','Тип_ошибки']]
    
merged = pd.merge(error_type_df[['PMID','num','error_type_reason','error_type']],
                df1,
                left_on=['PMID','num'],right_on=['PMID_статьи','Номер_критерия'],
                        how='left')
print(merged.shape)
for i in merged.drop(columns=['PMID_статьи','Номер_критерия','Почему_ошибка']).values:
    print(i[:2])
    print(f"LLM: {i[3]}; \nReason: {i[2]}")
    print(f"Expert: {i[4]}\n")

(33, 8)
['22845480' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a list of biomarker applications (background) with the study's primary subject.
Expert: The model confuses background keywords with the paper's focus

['23585220' 1]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated the absence of CRC mention as ambiguous rather than definitive exclusion.
Expert: nan

['23585220' 2]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated the absence of CRC in the population as ambiguous rather than definitive exclusion
Expert: nan

['23585220' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated the focus on side effects (excluding efficacy) as ambiguous rather than definitive
Expert: The model treats 'not mentioned' as 'possible'

['23719267' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated a list of affected cancers (background) as evidence of efficacy evaluation for CRC
Expert: The model treats 'not mentioned' as 'possible'

['23719267' 2]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated a background mention of CRC (ROS1 fusions) as evidence of intervention for CRC
Expert: nan

['23719267' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a list of cancers with ROS1 rearrangements (background) with specific inclusion
Expert: The model confuses background keywords with the paper's focus

['25139705' 1]
LLM: Confusing review/general discussion with primary study inclusion of subjects;
Reason: The model confused a review article mentioning treatments with primary study inclusion of patients
Expert: The model confuses background keywords with the paper's focus

['26468446' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a background list of ALK-associated diseases with study inclusion
Expert: The model confuses background keywords with the paper's focus

['26995877' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a background example in a review with the study's focus
Expert: The model confuses background keywords with the paper's focus

['28183697' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a list of responder types (background) with specific cohort inclusion
Expert: nan

['29466887' 1]
LLM: Confusing review/general discussion with primary study inclusion of subjects;
Reason: The model confused a policy analysis mentioning a disease with primary study inclusion of patients
Expert: The criteria is only partially met

['34898475' 2]
LLM: Confusing computational/in silico prediction with experimental investigation;
Reason: The model confused in silico prediction with actual experimental investigation
Expert: The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.

['34898475' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated the absence of efficacy evaluation (only in silico) as ambiguous
Expert: The model treats 'not mentioned' as 'possible'

['35343863' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated explicit limitation to NSCLC as ambiguous for CRC
Expert: The model treats 'not mentioned' as 'possible'

['35343863' 2]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated background mention of CRC (ROS1) as evidence of intervention for CRC
Expert: nan

['35343863' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a background list of ROS1 diseases with the study's focus
Expert: The model confuses background keywords with the paper's focus

['36129915' 2]
LLM: Confusing computational/in silico prediction with experimental investigation;
Reason: The model confused computational prediction with actual experimental investigation
Expert: The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.

['36627781' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated background mention of CRC (ALK) as evidence of efficacy evaluation
Expert: The model treats 'not mentioned' as 'possible'

['36627781' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a background list of ALK diseases with study investigation of CRC
Expert: The model confuses background keywords with the paper's focus

['36627781' 2]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated explicit focus on NSCLC as ambiguous for CRC intervention
Expert: nan

['36801912' 2]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated explicit exclusion from indications as ambiguous
Expert: nan

['36801912' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated explicit exclusion in abstract as ambiguous
Expert: The model treats 'not mentioned' as 'possible'

['37686423' 1]
LLM: Confusing review/general discussion with primary study inclusion of subjects;
Reason: The model confused a review discussing a disease with primary study inclusion of patients
Expert: The criteria is only partially met

['37773318' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model confused general mentions of activity with specific efficacy evaluation for CRC
Expert: The model confuses a general topic with the potential inclusion of specific data.

['37773318' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused a background citation in a review with primary study inclusion
Expert: The model confuses background keywords with the paper's focus

['37773318' 2]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused general mention in a broad review with specific investigation
Expert: The model equates keyword co-occurrence with keyword interaction.

['38378070' 2]
LLM: Confusing computational/in silico prediction with experimental investigation;
Reason: The model confused computational correlation with experimental investigation
Expert: The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.

['40140597' 1]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused background context/future plans with actual study population
Expert: nan

['40140597' 2]
LLM: Confusing background/contextual mention with study focus or inclusion;
Reason: The model confused background mention of CRC with specific intervention for CRC
Expert: nan

['40140597' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated lack of disease-specific data (general cohort) as ambiguous
Expert: nan

['41213063' 2]
LLM: Confusing computational/in silico prediction with experimental investigation;
Reason: The model confused computational prediction with experimental investigation
Expert: The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.

['41213063' 3]
LLM: Misinterpreting absence of data as ambiguity instead of definitive exclusion;
Reason: The model treated absence of therapeutic data (only computational) as ambiguous
Expert: The model treats 'not mentioned' as 'possible'

In [ ]:
outs

ErrorsAndClusters(reasoning="The errors can be clustered into four distinct root causes based on the cognitive mechanism of the failure:\n1. **Confusing Background/Example Mentions with Study Focus**: The model incorrectly interprets a disease mentioned in a list, background, or as an example as the primary subject of the study. This applies to Criteria 1 and 2.\n2. **Misinterpreting Study Design/Methodology**: The model fails to distinguish between primary studies (patients/samples) and reviews/policy analyses, or between experimental/clinical investigations and in silico/computational predictions. This applies to Criteria 1 and 2.\n3. **Treating Explicit Exclusion or Absence as Ambiguity**: The model assigns 'Uncertain' when the text explicitly excludes the condition, limits the scope to another disease, or completely lacks the required information, which should result in a 'No'. This applies to Criteria 1, 2, and 3.\n4. **Ignoring Population Specificity in Efficacy Evaluation**: The model fails to recognize that if", clusters=[Cluster(reasoning='The model conflates incidental mentions (lists, background, examples) with the primary study focus or inclusion.', index=0, name='Confusing background/example mentions with study focus', notable_pointers=['CRC listed as example of biomarker application', 'CRC mentioned in list of ROS1/ALK associated diseases', 'CRC cited illustratively in general review', 'Background mention mistaken for primary inclusion']), Cluster(reasoning='The model fails to distinguish between primary studies (patients/samples) and secondary studies (reviews/policy), or between experimental interventions and computational predictions.', index=1, name='Misinterpreting study design or methodology type', notable_pointers=['Review article mistaken for primary study with patients', 'Policy/economic analysis mistaken for patient inclusion', 'In silico prediction mistaken for experimental intervention', 'Computational screening mistaken for efficacy evaluation']), Cluster(reasoning="The model assigns 'Uncertain' instead of 'No' when the study explicitly excludes the condition, limits scope to another disease, or lacks the required information entirely.", index=2, name='Treating explicit exclusion or absence as ambiguity', notable_pointers=['Complete absence of CRC mention treated as uncertain', 'Explicit focus on NSCLC treated as uncertain for CRC', 'Explicit exclusion of CRC from indications treated as uncertain', 'Unspecified cancer type treated as uncertain instead of no']), Cluster(reasoning='The model fails to recognize that efficacy outcomes reported for a broad cohort (e.g., solid tumors) do not constitute specific efficacy data for the target disease (CRC).', index=3, name='Ignoring population specificity in efficacy evaluation', notable_pointers=['Efficacy reported for advanced solid tumors, not CRC', 'Response rates applied to other indications, not CRC', 'Lack of disease-specific data in broad cohort'])], errors=[Error(reasoning='Model confused a list of biomarker applications with the study focus.', error_index=0, cluster_index=0), Error(reasoning='Model treated complete absence of mention as ambiguous rather than definitive exclusion.', error_index=1, cluster_index=2), Error(reasoning='Model treated unspecified cancer type (absence of CRC) as ambiguous rather than definitive exclusion', error_index=2, cluster_index=2), Error(reasoning='Model treated explicit focus on side effects (excluding efficacy) as ambiguous.', error_index=3, cluster_index=2), Error(reasoning='Model treated mention in a list without efficacy evaluation as ambiguous.', error_index=4, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background mention of CRC as ambiguous.', error_index=5, cluster_index=2), Error(reasoning='Model confused a list of cancers with ROS1 rearrangements with specific inclusion of CRC patients.', error_index=6, cluster_index=0), Error(reasoning='Model confused a review article with a primary study involving patients.', error_index=7, cluster_index=1), Error(reasoning='Model confused a background mention in a list with actual study inclusion.', error_index=8, cluster_index=0), Error(reasoning='Model confused a background example with the study focus.', error_index=9, cluster_index=0), Error(reasoning='Model confused a list of responder types with a focused cohort.', error_index=10, cluster_index=0), Error(reasoning='Model confused a policy analysis with a study including patients.', error_index=11, cluster_index=1), Error(reasoning='Model confused in silico prediction with actual experimental investigation.', error_index=12, cluster_index=1), Error(reasoning='Model treated absence of efficacy evaluation (in silico only) as ambiguous.', error_index=13, cluster_index=2), Error(reasoning='Model treated explicit limitation to NSCLC as ambiguous for CRC.', error_index=14, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background CRC as ambiguous.', error_index=15, cluster_index=2), Error(reasoning='Model confused a background list of diseases with the study focus.', error_index=16, cluster_index=0), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=17, cluster_index=1), Error(reasoning='Model treated mention of CRC as disease involving ALK as implying efficacy evaluation.', error_index=18, cluster_index=2), Error(reasoning='Model confused a background mention with evidence of investigation.', error_index=19, cluster_index=0), Error(reasoning='Model treated explicit exclusion of CRC from indications as ambiguous.', error_index=20, cluster_index=2), Error(reasoning='Model treated explicit exclusion from approved indications as ambiguous.', error_index=21, cluster_index=2), Error(reasoning='Model treated explicit exclusion in abstract as ambiguous.', error_index=22, cluster_index=2), Error(reasoning='Model confused a review discussing a disease with a primary study involving patients.', error_index=23, cluster_index=1), Error(reasoning='Model failed to recognize efficacy outcomes were not specific to CRC.', error_index=24, cluster_index=3), Error(reasoning='Model confused a background citation with primary study inclusion.', error_index=25, cluster_index=0), Error(reasoning='Model confused general mention in a broad review with specific investigation.', error_index=26, cluster_index=0), Error(reasoning='Model confused computational correlation with experimental investigation.', error_index=27, cluster_index=1), Error(reasoning='Model confused background context/future plans with actual study population.', error_index=28, cluster_index=0), Error(reasoning='Model failed to notice study enrolled general solid tumors, not specifically CRC.', error_index=29, cluster_index=3), Error(reasoning='Model failed to recognize efficacy outcomes were for entire cohort, not specifically CRC.', error_index=30, cluster_index=3), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=31, cluster_index=1), Error(reasoning='Model treated computational predictions (no actual efficacy data) as ambiguous.', error_index=32, cluster_index=2)])

In [2]:
error_type_df = pd.read_csv('outputs/error_type_df.csv', index_col=0)
df_p_e = pd.read_csv('screening.csv')

from sklearn.model_selection import train_test_split
dfo = pd.read_csv('new_criteria_ana_en2.csv')
dfo['PMID'] = dfo['PMID'].astype(str)
dfo[['s1','s2','s3']] = dfo[['s1','s2','s3']].astype(int)
X = dfo.iloc[:,:1]
y = dfo.iloc[:,]
# stratify by accept/not accept. maybe instead by [1,1,0]?
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, 
                                                    random_state=42,stratify=dfo.accept)

errors_df, correct_df = main.find_mistakes(df_p_e, y_train)

a = correct_df.groupby('PMID').count()['num']
a[a==3].index.values


fin_condition='Colorectal cancer'
treatment='Crizotinib'
error_id_df = pd.read_csv('outputs/error_id_df.csv')
error_type_df, outs = main.find_error_clusters(error_id_df,
                                                fin_condition, treatment)

INFO:root: passing 1 queries to llama.cpp...

    eligibility_criteria = ["Does the study include patients, animal models, organoids, cell lines, or biological samples representing 'Colorectal cancer' as a studied disease/condition?", "Does the study investigate 'Crizotinib' as an intervention, treatment, exposure, or experimental factor for 'Colorectal cancer'?", "Does the study evaluate the therapeutic effectiveness or antitumor activity of 'Crizotinib' for 'Colorectal cancer' using clinically or biologically relevant efficacy outcomes?"]
    model_errors = error_index | criteria_num | error_description
0 | 1 | The model failed to distinguish between the study's primary subject (biomarkers) and the diseases listed as examples. It incorrectly assumed that mentioning CRC in a list of biomarker applications meant CRC was the studied condition, ignoring that the paper reviews biomarkers generally.
1 | 1 | The model incorrectly scored UNCERTAIN (0) instead of NO (-1). It failed to recognize that the complete absence of any mention of Colorectal Cancer in the abstract definitively excludes the study, rather than leaving the status ambiguous.
2 | 2 | The model incorrectly assigned 'Uncertain' (0) due to missing cancer type information, failing to recognize that the absence of 'Colorectal Cancer' in the study population explicitly means the criterion is not met, warranting a 'No' (-1) score.
3 | 3 | The model incorrectly scored UNCERTAIN because the cancer type was unspecified, failing to recognize that the study's focus on endocrine side effects definitively excludes it from evaluating antitumor activity, which warrants a NO score.
4 | 3 | The model incorrectly assigned UNCERTAIN (0) instead of NO (-1). It failed to recognize that mentioning a disease in a list of affected cancers without evaluating the drug's efficacy for that specific disease constitutes a definitive exclusion, not ambiguity.
5 | 2 | The model incorrectly classified the score as Uncertain (0) instead of No (-1). It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning Colorectal Cancer only as a site of ROS1 fusions without linking it to Crizotinib, constitutes a definitive negative for the specific intervention-disease pair.
6 | 1 | The model incorrectly assumed that listing colorectal cancer among various cancers with ROS1 rearrangements meant the study specifically included CRC patients or samples, failing to recognize it was just a general review of ROS1 across multiple cancer types.
7 | 1 | The model failed to distinguish between a review article summarizing existing treatments and a primary study involving original subjects. It incorrectly assumed that mentioning colorectal cancer as a condition treated by approved agents constituted 'including' patients or samples in the study.
8 | 1 | The model mistook a background mention of colorectal cancer in a list of ALK-associated diseases for actual study inclusion, ignoring that the research focuses on NSCLC and general mechanisms without specific CRC data.
9 | 1 | The model incorrectly classified a background example of colorectal cancer as the study's focus, failing to recognize that the abstract is a general review where CRC is only cited illustratively.
10 | 1 | The model erroneously classified the study as including CRC patients based solely on a list of responder types, ignoring the expert's point that CRC was not a focused cohort with specific analysis or models, rendering the inclusion uncertain.
11 | 1 | The model failed to distinguish between a policy/economic analysis mentioning a disease and a study that actually includes patients or biological samples as subjects. It incorrectly scored YES because CRC was mentioned, ignoring the requirement for direct inclusion of patients/samples.
12 | 2 | The model incorrectly classified an in silico prediction of potential efficacy as an investigation of the drug as an intervention, ignoring that no actual treatment study was conducted.
13 | 3 | The model incorrectly classified the absence of efficacy evaluation as 'Uncertain' (0) instead of 'No' (-1). Since the study only performed in silico screening and explicitly did not assess therapeutic effectiveness, the criterion is definitively not met.
14 | 3 | The model failed to recognize that explicitly limiting Crizotinib's efficacy to NSCLC constitutes a definitive exclusion for colorectal cancer, incorrectly labeling it as uncertain instead of a clear negative.
15 | 2 | The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that explicitly linking Crizotinib to NSCLC treatment, while mentioning CRC only as a background condition for ROS1 involvement, definitively excludes Crizotinib as an intervention for CRC in this study.
16 | 1 | The model mistakenly treated a background list of diseases associated with ROS1 as the study's focus, ignoring that the review exclusively covers NSCLC and excludes CRC from its scope.
17 | 2 | The model confused computational prediction of drug candidates with actual experimental investigation of the intervention, failing to recognize that bioinformatics inference does not constitute investigating the drug as a treatment.
18 | 3 | The model failed to recognize that mentioning CRC as a disease involving ALK does not imply evaluating Crizotinib's efficacy for it. The study focuses on ALK inhibitors for ALK-dependent cancers like NSCLC, so efficacy for CRC is explicitly not assessed, requiring a -1, not 0.
19 | 1 | The model mistakenly treated a background mention of colorectal cancer in a list of ALK-associated diseases as evidence that the study investigates CRC, ignoring that the review focuses on ALK inhibitors generally and NSCLC specifically.
20 | 2 | The model failed to recognize that mentioning Crizotinib for NSCLC explicitly excludes it as an intervention for colorectal cancer in this context, leading to an incorrect UNCERTAIN score instead of NO.
21 | 2 | The model failed to recognize that the explicit exclusion of colorectal cancer from the approved indications for the studied regimen implies crizotinib is not being investigated for this specific cancer type, leading to an incorrect UNCERTAIN score instead of NO.
22 | 3 | The model failed to recognize the explicit exclusion of colorectal cancer in the abstract, incorrectly labeling the eligibility as uncertain instead of definitively negative.
23 | 1 | The model failed to distinguish between a review article discussing a disease and a primary study involving actual patients or biological samples of that disease, incorrectly assuming mention implies inclusion of study subjects.
24 | 3 | The model conflated general mentions of activity in colorectal cancer with specific efficacy evaluation, ignoring that the cited response rates applied only to other approved indications, not CRC.
25 | 1 | The model mistook a background citation of colorectal cancer in a list of examples for primary study inclusion, failing to recognize that the study is a review where CRC is not the main focus.
26 | 2 | The model erroneously equated the general mention of Crizotinib and CRC in a broad review with a specific investigation of Crizotinib for CRC, ignoring the lack of focused data or primary intent.
27 | 2 | The model incorrectly classified a computational drug sensitivity correlation from a database as an experimental investigation of Crizotinib as an intervention, ignoring that the study focuses on biomarker identification, not drug testing.
28 | 1 | The model conflated background context and future plans with the actual study population, ignoring that the trial enrolled patients with advanced solid tumors generally, not specifically colorectal cancer.
29 | 2 | The model ignored the patient population constraint. It confirmed Crizotinib was used but failed to notice the study enrolled patients with 'advanced solid tumours' generally, not specifically Colorectal Cancer, despite CRC being mentioned only in background/future context.
30 | 3 | The model failed to recognize that the efficacy outcomes were reported for the entire cohort of advanced solid tumors, not specifically for colorectal cancer patients, thus missing the lack of disease-specific data.
31 | 2 | The model incorrectly classified computational drug sensitivity prediction as an experimental investigation of the drug as an intervention, failing to distinguish between in silico modeling and actual clinical or experimental treatment.
32 | 3 | The model incorrectly assigned 'Uncertain' instead of 'No'. It failed to recognize that reporting only computational drug sensitivity predictions, without any actual therapeutic effectiveness or antitumor activity data, definitively fails the criterion, warranting a 'No' score.

    your_response =

http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf

INFO:root:fresh response in asynch: reasoning="The errors can be clustered into four distinct root causes based on the cognitive mechanism of the failure:\n1. **Confusing Background/Example Mentions with Study Focus**: The model incorrectly interprets a disease mentioned in a list, background, or as an example as the primary subject of the study. This applies to Criteria 1 and 2.\n2. **Misinterpreting Study Design/Methodology**: The model fails to distinguish between primary studies (patients/samples) and reviews/policy analyses, or between experimental/clinical investigations and in silico/computational predictions. This applies to Criteria 1 and 2.\n3. **Treating Explicit Exclusion or Absence as Ambiguity**: The model assigns 'Uncertain' when the text explicitly excludes the condition, limits the scope to another disease, or completely lacks the required information, which should result in a 'No'. This applies to Criteria 1, 2, and 3.\n4. **Ignoring Population Specificity in Efficacy Evaluation**: The model fails to recognize that if" clusters=[Cluster(reasoning='The model conflates incidental mentions (lists, background, examples) with the primary study focus or inclusion.', index=0, name='Confusing background/example mentions with study focus', notable_pointers=['CRC listed as example of biomarker application', 'CRC mentioned in list of ROS1/ALK associated diseases', 'CRC cited illustratively in general review', 'Background mention mistaken for primary inclusion']), Cluster(reasoning='The model fails to distinguish between primary studies (patients/samples) and secondary studies (reviews/policy), or between experimental interventions and computational predictions.', index=1, name='Misinterpreting study design or methodology type', notable_pointers=['Review article mistaken for primary study with patients', 'Policy/economic analysis mistaken for patient inclusion', 'In silico prediction mistaken for experimental intervention', 'Computational screening mistaken for efficacy evaluation']), Cluster(reasoning="The model assigns 'Uncertain' instead of 'No' when the study explicitly excludes the condition, limits scope to another disease, or lacks the required information entirely.", index=2, name='Treating explicit exclusion or absence as ambiguity', notable_pointers=['Complete absence of CRC mention treated as uncertain', 'Explicit focus on NSCLC treated as uncertain for CRC', 'Explicit exclusion of CRC from indications treated as uncertain', 'Unspecified cancer type treated as uncertain instead of no']), Cluster(reasoning='The model fails to recognize that efficacy outcomes reported for a broad cohort (e.g., solid tumors) do not constitute specific efficacy data for the target disease (CRC).', index=3, name='Ignoring population specificity in efficacy evaluation', notable_pointers=['Efficacy reported for advanced solid tumors, not CRC', 'Response rates applied to other indications, not CRC', 'Lack of disease-specific data in broad cohort'])] errors=[Error(reasoning='Model confused a list of biomarker applications with the study focus.', error_index=0, cluster_index=0), Error(reasoning='Model treated complete absence of mention as ambiguous rather than definitive exclusion.', error_index=1, cluster_index=2), Error(reasoning='Model treated unspecified cancer type (absence of CRC) as ambiguous rather than definitive exclusion', error_index=2, cluster_index=2), Error(reasoning='Model treated explicit focus on side effects (excluding efficacy) as ambiguous.', error_index=3, cluster_index=2), Error(reasoning='Model treated mention in a list without efficacy evaluation as ambiguous.', error_index=4, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background mention of CRC as ambiguous.', error_index=5, cluster_index=2), Error(reasoning='Model confused a list of cancers with ROS1 rearrangements with specific inclusion of CRC patients.', error_index=6, cluster_index=0), Error(reasoning='Model confused a review article with a primary study involving patients.', error_index=7, cluster_index=1), Error(reasoning='Model confused a background mention in a list with actual study inclusion.', error_index=8, cluster_index=0), Error(reasoning='Model confused a background example with the study focus.', error_index=9, cluster_index=0), Error(reasoning='Model confused a list of responder types with a focused cohort.', error_index=10, cluster_index=0), Error(reasoning='Model confused a policy analysis with a study including patients.', error_index=11, cluster_index=1), Error(reasoning='Model confused in silico prediction with actual experimental investigation.', error_index=12, cluster_index=1), Error(reasoning='Model treated absence of efficacy evaluation (in silico only) as ambiguous.', error_index=13, cluster_index=2), Error(reasoning='Model treated explicit limitation to NSCLC as ambiguous for CRC.', error_index=14, cluster_index=2), Error(reasoning='Model treated explicit link to NSCLC and background CRC as ambiguous.', error_index=15, cluster_index=2), Error(reasoning='Model confused a background list of diseases with the study focus.', error_index=16, cluster_index=0), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=17, cluster_index=1), Error(reasoning='Model treated mention of CRC as disease involving ALK as implying efficacy evaluation.', error_index=18, cluster_index=2), Error(reasoning='Model confused a background mention with evidence of investigation.', error_index=19, cluster_index=0), Error(reasoning='Model treated explicit exclusion of CRC from indications as ambiguous.', error_index=20, cluster_index=2), Error(reasoning='Model treated explicit exclusion from approved indications as ambiguous.', error_index=21, cluster_index=2), Error(reasoning='Model treated explicit exclusion in abstract as ambiguous.', error_index=22, cluster_index=2), Error(reasoning='Model confused a review discussing a disease with a primary study involving patients.', error_index=23, cluster_index=1), Error(reasoning='Model failed to recognize efficacy outcomes were not specific to CRC.', error_index=24, cluster_index=3), Error(reasoning='Model confused a background citation with primary study inclusion.', error_index=25, cluster_index=0), Error(reasoning='Model confused general mention in a broad review with specific investigation.', error_index=26, cluster_index=0), Error(reasoning='Model confused computational correlation with experimental investigation.', error_index=27, cluster_index=1), Error(reasoning='Model confused background context/future plans with actual study population.', error_index=28, cluster_index=0), Error(reasoning='Model failed to notice study enrolled general solid tumors, not specifically CRC.', error_index=29, cluster_index=3), Error(reasoning='Model failed to recognize efficacy outcomes were for entire cohort, not specifically CRC.', error_index=30, cluster_index=3), Error(reasoning='Model confused computational prediction with experimental investigation.', error_index=31, cluster_index=1), Error(reasoning='Model treated computational predictions (no actual efficacy data) as ambiguous.', error_index=32, cluster_index=2)]
INFO:root:

In [3]:

z,alldf = main.augment_samples(error_type_df,correct_df,
                        outs,
                        a[a==3].index.values[:1],
                        fin_condition,treatment)

INFO:root: passing 1 queries to llama.cpp...

http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf

INFO:root:fresh response in asynch: new_samples=[ScreeningSample(error_type_index=0, reasoning='Modified the abstract to mention Colorectal Cancer (CRC) only in the background context as an example of a disease where HGF/c-Met is relevant, while the actual study focuses exclusively on breast and lung cancer models. This tests if the model incorrectly identifies CRC as a studied population based on background mentions.', new_abstract='HGF/c-Met pathway is one of the mediators of sunitinib-induced tumor cell type-dependent metastasis. Recent studies in several tumor models, including colorectal cancer (CRC), indicated that treatment with angiogenic inhibitors may trigger induction of metastasis to other organs. Here we investigated modes of resistance and invasion in several tumor cell lines including 4T1 (breast) and H460 (lung) using sunitinib at doses comparable to clinically utilized regimen. In comparison with vehicle-treated tumors, sunitinib increased metastasis to lung in 4T1 tumors. However, the same treatment did not induce invasiveness in H460 tumors, further suggesting that accelerating metastasis during treatment with angiogenic inhibitors is tumor cell-type dependent. Interestingly, Crizotinib (a dual inhibitor of c-Met and ALK pathways) as single agent or in combination with sunitinib reduced metastasis in all models tested suggesting a role for c-Met/HGF pathway in intrinsic- or sunitinib-induced-metastasis. Moreover, ELISA data showed that while c-Met is highly enriched in tumor cells, HGF is secreted mainly by the stroma (mouse HGF) suggesting a paracrine fashion for c-Met pathway activation in the tumors. In conclusion, our findings indicate that sunitinib-induced metastasis is tumor cell-type dependent and further supports a rationale for combination of anti-angiogenics and c-Met inhibition in the clinic.'), ScreeningSample(error_type_index=1, reasoning="Removed all mentions of Colorectal Cancer (CRC) and the Colo205 cell line, replacing them with a generic 'solid tumor' description or omitting the specific cancer type for that model. This tests if the model treats the absence of explicit CRC mention as ambiguity/uncertainty rather than a clear exclusion.", new_abstract='HGF/c-Met pathway is one of the mediators of sunitinib-induced tumor cell type-dependent metastasis. Recent studies in several tumor models indicated that treatment with angiogenic inhibitors may trigger induction of metastasis to other organs. Here we investigated modes of resistance and invasion in several tumor cell lines including 4T1 (breast), H460 (lung) and a generic solid tumor line using sunitinib at doses comparable to clinically utilized regimen. In comparison with vehicle-treated tumors, sunitinib increased metastasis to lung in 4T1 tumors and to peritoneal lymph node in the solid tumor line. However, the same treatment did not induce invasiveness in H460 tumors, further suggesting that accelerating metastasis during treatment with angiogenic inhibitors is tumor cell-type dependent. Interestingly, Crizotinib (a dual inhibitor of c-Met and ALK pathways) as single agent or in combination with sunitinib reduced metastasis in all models tested suggesting a role for c-Met/HGF pathway in intrinsic- or sunitinib-induced-metastasis. Moreover, ELISA data showed that while c-Met is highly enriched in tumor cells, HGF is secreted mainly by the stroma (mouse HGF) suggesting a paracrine fashion for c-Met pathway activation in the tumors. In conclusion, our findings indicate that sunitinib-induced metastasis is tumor cell-type dependent and further supports a rationale for combination of anti-angiogenics and c-Met inhibition in the clinic.'), ScreeningSample(error_type_index=2, reasoning='Changed the study design from an experimental investigation using cell lines and animal models to a computational in silico prediction study. This tests if the model mistakes a computational screening/prediction study for a primary study with biological samples/patients.', new_abstract='HGF/c-Met pathway is one of the mediators of sunitinib-induced tumor cell type-dependent metastasis. Recent studies in several tumor models indicated that treatment with angiogenic inhibitors may trigger induction of metastasis to other organs. Here we performed an in silico computational screening to investigate modes of resistance and invasion in several tumor cell lines including 4T1 (breast), H460 (lung) and Colo205 (colorectal) using sunitinib at doses comparable to clinically utilized regimen. Using molecular docking simulations, we predicted that sunitinib increased metastasis potential in 4T1 tumors and Colo205 tumors. However, the simulation did not predict invasiveness in H460 tumors, further suggesting that accelerating metastasis during treatment with angiogenic inhibitors is tumor cell-type dependent. Interestingly, computational models predicted that Crizotinib (a dual inhibitor of c-Met and ALK pathways) as single agent or in combination with sunitinib reduced metastasis in all models tested suggesting a role for c-Met/HGF pathway in intrinsic- or sunitinib-induced-metastasis. Moreover, literature mining data showed that while c-Met is highly enriched in tumor cells, HGF is secreted mainly by the stroma suggesting a paracrine fashion for c-Met pathway activation in the tumors. In conclusion, our computational findings indicate that sunitinib-induced metastasis is tumor cell-type dependent and further supports a rationale for combination of anti-angiogenics and c-Met inhibition in the clinic.'), ScreeningSample(error_type_index=3, reasoning="Modified the abstract to state that Crizotinib was tested in a broad cohort of 'advanced solid tumors' without specifying efficacy outcomes for Colorectal Cancer specifically, even though CRC was part of the cohort. This tests if the model ignores the lack of disease-specific efficacy data for CRC.", new_abstract='HGF/c-Met pathway is one of the mediators of sunitinib-induced tumor cell type-dependent metastasis. Recent studies in several tumor models indicated that treatment with angiogenic inhibitors may trigger induction of metastasis to other organs. Here we investigated modes of resistance and invasion in a broad cohort of advanced solid tumors including breast, lung, and colorectal cancer using sunitinib at doses comparable to clinically utilized regimen. In comparison with vehicle-treated tumors, sunitinib increased metastasis in the overall cohort. Interestingly, Crizotinib (a dual inhibitor of c-Met and ALK pathways) as single agent or in combination with sunitinib reduced metastasis in the overall advanced solid tumor cohort suggesting a role for c-Met/HGF pathway in intrinsic- or sunitinib-induced-metastasis. Moreover, ELISA data showed that while c-Met is highly enriched in tumor cells, HGF is secreted mainly by the stroma (mouse HGF) suggesting a paracrine fashion for c-Met pathway activation in the tumors. In conclusion, our findings indicate that sunitinib-induced metastasis is tumor cell-type dependent and further supports a rationale for combination of anti-angiogenics and c-Met inhibition in the clinic.')]
INFO:root:

In [4]:
error_type_df.error_type.unique()

array(['Confusing background/example mentions with study focus',
       'Treating explicit exclusion or absence as ambiguity',
       'Misinterpreting study design or methodology type',
       'Ignoring population specificity in efficacy evaluation'],
      dtype=object)

In [5]:
correct_score,alldf = main.add_correct_scores(z,
                    fin_condition,treatment)

INFO:root: passing 1 queries to llama.cpp...

http://localhost:8501/v1 /models/Qwen3.6-27B-UD-Q4_K_XL.gguf

INFO:root:fresh response in asynch: new_samples=[SampleScore(error_type_index=0, reasoning='CRC is mentioned only in the background as an example of prior studies. The actual investigation focuses exclusively on breast (4T1) and lung (H460) models. This tests if the model incorrectly includes CRC based on background context.', new_ground_truth=[CriteriaScore(criteria_index=0, new_expert_rationale="CRC is mentioned only in the background ('Recent studies... including colorectal cancer'). The study explicitly investigates '4T1 (breast) and H460 (lung)' models. No CRC samples were studied.", new_expert_score=-1), CriteriaScore(criteria_index=1, new_expert_rationale='Since no CRC models were included in the study, Crizotinib was not investigated for CRC.', new_expert_score=-1), CriteriaScore(criteria_index=2, new_expert_rationale='No efficacy outcomes for Crizotinib in CRC are reported because CRC was not a studied population.', new_expert_score=-1)]), SampleScore(error_type_index=1, reasoning='All mentions of CRC and the Colo205 cell line were removed. The study now lists breast, lung, and a generic solid tumor line. This tests if the model treats the absence of CRC as uncertainty rather than exclusion.', new_ground_truth=[CriteriaScore(criteria_index=0, new_expert_rationale="The abstract lists '4T1 (breast), H460 (lung) and a generic solid tumor line'. There is no mention of Colorectal Cancer or specific CRC cell lines. Thus, CRC is not included.", new_expert_score=-1), CriteriaScore(criteria_index=1, new_expert_rationale='Crizotinib was tested in the listed models (breast, lung, generic solid tumor), but not specifically in CRC models.', new_expert_score=-1), CriteriaScore(criteria_index=2, new_expert_rationale='No efficacy data for Crizotinib in CRC is provided as CRC was not part of the study cohort.', new_expert_score=-1)]), SampleScore(error_type_index=2, reasoning="The study design is changed to 'in silico computational screening' and 'molecular docking simulations'. This tests if the model mistakes a computational prediction for a primary biological study with actual samples.", new_ground_truth=[CriteriaScore(criteria_index=0, new_expert_rationale="The study is an 'in silico computational screening' using 'molecular docking simulations'. It does not use actual patients, animal models, organoids, cell lines, or biological samples.", new_expert_score=-1), CriteriaScore(criteria_index=1, new_expert_rationale="The investigation is computational ('predicted that sunitinib increased...'). It does not involve actual experimental intervention with Crizotinib in biological CRC models.", new_expert_score=-1), CriteriaScore(criteria_index=2, new_expert_rationale="Outcomes are based on 'computational models predicted' and 'literature mining', not clinically or biologically relevant efficacy outcomes from actual samples.", new_expert_score=-1)]), SampleScore(error_type_index=3, reasoning="CRC is part of a 'broad cohort of advanced solid tumors', but efficacy is reported only for the 'overall cohort'. This tests if the model ignores the lack of disease-specific efficacy data for CRC.", new_ground_truth=[CriteriaScore(criteria_index=0, new_expert_rationale="The study investigates a 'broad cohort of advanced solid tumors including breast, lung, and colorectal cancer'. CRC is explicitly included as a studied condition.", new_expert_score=1), CriteriaScore(criteria_index=1, new_expert_rationale="Crizotinib was tested in the cohort that includes CRC ('reduced metastasis in the overall advanced solid tumor cohort').", new_expert_score=1), CriteriaScore(criteria_index=2, new_expert_rationale="Efficacy is reported for the 'overall advanced solid tumor cohort'. There is no specific efficacy outcome reported for Colorectal Cancer alone, making it uncertain if it was effective specifically for CRC.", new_expert_score=0)])]
INFO:root:

In [7]:
alldf

,error_type_index,reasoning,criteria_index,new_expert_rationale,new_expert_score
0,0,CRC is mentioned only in the background as an ...,0,CRC is mentioned only in the background ('Rece...,-1
1,0,CRC is mentioned only in the background as an ...,1,Since no CRC models were included in the study...,-1
2,0,CRC is mentioned only in the background as an ...,2,No efficacy outcomes for Crizotinib in CRC are...,-1
3,1,All mentions of CRC and the Colo205 cell line ...,0,"The abstract lists '4T1 (breast), H460 (lung) ...",-1
4,1,All mentions of CRC and the Colo205 cell line ...,1,Crizotinib was tested in the listed models (br...,-1
5,1,All mentions of CRC and the Colo205 cell line ...,2,No efficacy data for Crizotinib in CRC is prov...,-1
6,2,The study design is changed to 'in silico comp...,0,The study is an 'in silico computational scree...,-1
7,2,The study design is changed to 'in silico comp...,1,The investigation is computational ('predicted...,-1
8,2,The study design is changed to 'in silico comp...,2,Outcomes are based on 'computational models pr...,-1
9,3,CRC is part of a 'broad cohort of advanced sol...,0,The study investigates a 'broad cohort of adva...,1
10,3,CRC is part of a 'broad cohort of advanced sol...,1,Crizotinib was tested in the cohort that inclu...,1
11,3,CRC is part of a 'broad cohort of advanced sol...,2,Efficacy is reported for the 'overall advanced...,0

## fixing types of errors

In [ ]:
df = pd.read_csv('common_errors.csv',sep=';')
chosen_cols = df.columns[~df.columns.isin(['контекст/уточнения'])]
df = df[chosen_cols].dropna(how='all')
df['Оценка_Эксперт']=df['Оценка_Эксперт'].astype(int)
df['Новая оценка эксперта'] = df[['Новая оценка эксперта','Тип_ошибки']].apply(lambda x: x['Новая оценка эксперта'] \
                                                                               if x['Тип_ошибки']!='In silico вместо фактического применения' else None,
                                                                               axis=1)
df['Оценка_Эксперт'] = df[['Оценка_Эксперт','Новая оценка эксперта']].apply(lambda x: int(x['Новая оценка эксперта']) \
                                                     if not pd.isna(x['Новая оценка эксперта']) else x['Оценка_Эксперт'],
                                                     axis=1)
df['Обоснование_Эксперт'] = df[['Обоснование_Эксперт','Новое обосновение эксперта']].apply(lambda x: x['Новое обосновение эксперта'] \
                                                     if not pd.isna(x['Новое обосновение эксперта']) else x['Обоснование_Эксперт'],
                                                     axis=1)
df['Почему_ошибка'] = df[['Почему_ошибка','Новое почему ошибка']].apply(lambda x: x['Новое почему ошибка'] \
                                                     if not pd.isna(x['Новое почему ошибка']) else x['Почему_ошибка'],
                                                     axis=1)
df['Тип_ошибки'] = df[['Новый тип ошибки','Тип_ошибки']].apply(lambda x: x['Новый тип ошибки'] if (not pd.isna(x['Новый тип ошибки'])) else x['Тип_ошибки'],
                                                         axis=1)

'In silico вместо фактического применения'
'The model mistakes a diagnostic/imaging tool for a therapeutic intervention.'

df.loc[df['Тип_ошибки'].isin(['In silico вместо фактического применения',
                         'The model mistakes a diagnostic/imaging tool for a therapeutic intervention.']),
       'Тип_ошибки'] = 'The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.'
df.loc[df['Тип_ошибки']=='The criteria is partially met', 'Тип_ошибки'] = 'The criteria is only partially met'
print(df.shape, df[df['Оценка_ЛЛМ']!=df['Оценка_Эксперт']].shape)
df = df[df['Оценка_ЛЛМ']!=df['Оценка_Эксперт']].iloc[:,:8]
#df.to_csv('common_errors_fixed.csv',index=False)
df.head(2)

(40, 12) (35, 12)

,PMID_статьи,Номер_критерия,Оценка_ЛЛМ,Обоснование_LLM,Оценка_Эксперт,Обоснование_Эксперт,Почему_ошибка,Тип_ошибки
0,25139705.0,1.0,1.0,The text explicitly lists 'colorectal cancer' ...,-1.0,"Это обзорная статья, обобщающая текущие достиж...",LLM приняла упоминание КРР в обзоре как фокус ...,The model confuses background keywords with th...
1,31399568.0,1.0,1.0,The text explicitly states that 'ROS1 gene rea...,-1.0,В абстракте крр упомянут как один из примеров ...,LLM интерпретировала КРР как изучаемое заболев...,The model confuses background keywords with th...

In [60]:
df['Тип_ошибки'].value_counts()

Тип_ошибки
The model confuses background keywords with the paper's focus                                            14
The model treats 'not mentioned' as 'possible'                                                           11
The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.     5
The criteria is only partially met                                                                        2
The model equates keyword co-occurrence with keyword interaction.                                         1
The model mistakes a proposed idea for a concept under study.                                             1
The model confuses a general topic with the potential inclusion of specific data.                         1
Name: count, dtype: int64

## translate

In [5]:
%pip uninstall -y googletrans 
%pip install googletrans-curl

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping googletrans as it is not installed.

Collecting googletrans-curl
  Using cached googletrans_curl-4.1.0-py3-none-any.whl.metadata (9.1 kB)
Collecting curl-cffi>=0.7.0 (from googletrans-curl)
  Using cached curl_cffi-0.16.3-cp310-abi3-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: httpx>=0.27.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx[http2]>=0.27.2->googletrans-curl) (0.28.1)
Collecting cffi>=2.0.0 (from curl-cffi>=0.7.0->googletrans-curl)
  Using cached cffi-2.1.1-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from curl-cffi>=0.7.0->googletrans-curl) (2026.1.4)
Collecting pycparser (from cffi>=2.0.0->curl-cffi>=0.7.0->googletrans-curl)
  Using cached pycparser-3.11-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: anyio in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (4.12.1)
Requirement already satisfied: httpcore==1.* in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (1.0.9)
Requirement already satisfied: idna in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (3.11)
Requirement already satisfied: h11>=0.16 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpcore==1.*->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (0.16.0)
Requirement already satisfied: h2<5,>=3 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx[http2]>=0.27.2->googletrans-curl) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in d:\programs\anaconda\envs\llms\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans-curl) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in d:\programs\anaconda\envs\llms\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans-curl) (4.1.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (1.3.0)
Requirement already satisfied: typing_extensions>=4.5 in d:\programs\anaconda\envs\llms\lib\site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (4.15.0)
Using cached googletrans_curl-4.1.0-py3-none-any.whl (21 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 8.5 MB/s  0:00:00
Downloading cffi-2.1.1-cp310-cp310-win_amd64.whl (185 kB)
Downloading pycparser-3.11-py3-none-any.whl (51 kB)
Installing collected packages: pycparser, cffi, curl-cffi, googletrans-curl

   ---------- ----------------------------- 1/4 [cffi]
   ---------- ----------------------------- 1/4 [cffi]
   ---------- ----------------------------- 1/4 [cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   ------------------------------ --------- 3/4 [googletrans-curl]
   ---------------------------------------- 4/4 [googletrans-curl]

Successfully installed cffi-2.1.1 curl-cffi-0.16.3 googletrans-curl-4.1.0 pycparser-3.11
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script cffi-gen-src.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script curl-cffi.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script translate.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text=['В статье описывается клинический случай 19-летнего пациента с злокачественной перитонеальной мезотелиомой',
       'Кризотиниб применялся для лечения мезотелиомы',
       'Эффективность кризотиниба для крр не оценивается','Кризотиниб упоминается в абстракте, но в связи с нмрл и транслокациями ALK']
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
 'Crizotinib has been used to treat mesothelioma',
 'The effectiveness of crizotinib for CRC has not been assessed',
 'Crizotinib is mentioned in the abstract, but in association with NSCLC and ALK translocations']

In [ ]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text = (dfo.iloc[:,4:].values).reshape(-1)
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
 'Crizotinib has been used to treat mesothelioma',
 'The effectiveness of crizotinib for CRC has not been assessed.',
 '"16 colorectal cancer cases"',
 'The abstract states that patients received inhibitors of various signaling pathways, including ALK/ROS1. Although crizotinib is an ALK/ROS1 inhibitor, it is not explicitly named in the abstract. We cannot confirm that it was the specific drug used in patients (it could be ceritinib, alectinib, lorlatinib, etc.)',
 'The abstract provides general data for the cohort (4 patients with CRC had a response), but is not linked to a specific drug.',
 'This is a review article summarizing current advances in targeted therapy for solid tumors. It does not include original patients, models or samples',
 'Crizotinib is mentioned in the abstract, but in association with NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 'The study uses the CRC cell line Colo205 and related animal tumor models',
 'It is stated that crizotinib (both monotherapy and combination) was used to evaluate the effect on metastasis, and this effect was observed in all models tested, including Colo205',
 'The study evaluates the biologically and clinically relevant preclinical outcome of reduced metastasis',
 'The abstract mentions CRC as one example of tumors where ROS1 rearrangements may be observed',
 'Crizotinib is mentioned as a drug to which patients have developed resistance',
 'The study evaluates the effectiveness of the new drug DS-6051b, not crizotinib',
 'CRC is mentioned as an example ("KRAS against the use of cetuximab and panitumumab in colorectal cancer")',
 'Crizotinib mentioned in the context of NSCLC and ALK fusions',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'A cohort of 1889 CRC samples is analyzed',
 'Crizotinib is mentioned in the introduction as a drug that has shown good results in the treatment of lung cancer with ALK/ROS1 rearrangements',
 'Therapeutic efficacy assessment for CRC is not available',
 'CRC cell line - KM12SM ("the KM12SM colorectal cancer cells containing the TPM3-NTRK1 gene fusion"). Corresponding animal models are also used (“in in vivo KM12SM cell models”)',
 'In vitro: "KM12SM cells were sensitive to the tropomyosin-related kinase-A inhibitors crizotinib and entrectinib". In vivo: "in in vivo KM12SM cell models, treatment with crizotinib delayed the progression of liver metastases..."',
 'The antitumor activity of crizotinib in the CRC model (KM12SM) is assessed by delaying the progression of metastases: “treatment with crizotinib delayed the progression of liver metastases, but not that of brain tumors”',
 '"human colorectal cancer (CRC) cell line (HCA-7)"; "CRC tissue microarray"',
 '"Addition of the dual MET/RON tyrosine kinase inhibitor, crizotinib, restored cetuximab sensitivity in SC." Crizotinib is used to overcome cetuximab resistance in a CRC model',
 'Evaluates the therapeutic efficacy of crizotinib based on the biologically significant outcome of “restored cetuximab sensitivity in SC.”',
 'CRC is mentioned only once in the introduction as an example of a disease associated with ROS1 ("which is involved in the formation of non-small cell lung cancer (NSCLC), gastric adenocarcinoma, colorectal cancer, and other malignant tumors")',
 'Crizotinib is mentioned in the context of treatment of NSCLC: 1. "only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC" 2. "Since the approval of crizotinib as multi-targeted ALK/MET/ROS1 kinase inhibitor for ALK-mutated NSCLC therapy"',
 'All discussion of the effectiveness of crizotinib applies to NSCLC',
 'The title refers to a patient with metastatic colorectal cancer: "Metastatic Colorectal Carcinoma Patient". There is a description of a patient with CRC',
 'Crizotinib (along with Alectinib and Lorlatinib) was used as a treatment for the patient: "Clinical Responses to Crizotinib, Alectinib, and Lorlatinib..."',
 'The name indicates "Clinical Responses", which involves assessing clinical response. However, without an abstract it is impossible to confirm: Which outcomes were assessed (ORR, PFS, OS, etc.); Was quantitative data provided; What was the specific response to crizotinib (given that there are three drugs mentioned in the title)',
 'CRC is mentioned once in the introduction as an example of a disease associated with ROS1: "ROS1 plays an important role in different malignancies including glioblastoma, colorectal cancer, gastric adenocarcinoma..."',
 'Crizotinib is mentioned exclusively in the context of the treatment of lung cancer: "After Crizotinib approval by FDA for the management of ALK-rearranged lung cancer..."',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'CRC is mentioned in the list of tumors in which ALK inhibitor activity is described ("colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer"), but this is only a mention in the list, and not the subject of primary research',
 'The review does not specifically target crizotinib for colorectal cancer - it is a review where CRC is just one of many tumor types mentioned. Without the full text, it is unclear how much detail the use of crizotinib in CRC is covered',
 'The abstract provides response rates (~50-85%), but these relate to approved indications (NSCLC, IMT, ALCL), not CRC',
 'The current study includes patients with a mixed population of solid tumors, not focusing on CRC. Although the Background section mentions a previous study on CRC xenografts (“We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth”). The Methods section states: "patients with advanced solid tumors received PD-0325901 with crizotinib" - without mentioning CRC as a specific population',
 'There is no indication in the abstract that the 25 patients included patients with CRC or that CRC was the target indication. Crizotinib used in combination with PD-0325901 in a mixed population',
 'Evaluates the effectiveness of the PD-0325901/crizotinib combination for solid tumors in general: "The best clinical response was stable disease in seven patients (29%)." Outcome is presented for the entire cohort, without breakdown by tumor type',
 'CRC cells in vitro (“specifically binds to c-Met in CRC cells”), mice with CRC tumors in vivo (“c-Met positive tumor-bearing mice”), etc.',
 'Used as a structural basis for the creation of a diagnostic fluorescent probe Crizotinib-PEG4-MPA. The text states: "we have developed a new small molecular fluorescence probe, namely Crizotinib-PEG4-MPA" - this is a modified molecule where crizotinib serves as a targeting element for binding to c-Met, but not as an independent drug for treatment',
 'The diagnostic effectiveness of the fluorescent probe is assessed, not the therapeutic effectiveness',
 '"We analyzed 26 MSI-High and 558 non-MSI-High CRC tumors", "We tested CRC cell lines", "Using an in-vivo CRC xenograft model"',
 '"tested CRC cell lines for sensitivity to MMC plus crizotinib" и "combined crizotinib and MMC therapy"',
 'In vitro:"increased apoptosis" и "synergistic anti-cancer effect (CI = 0.006-0.74)" In vivo: "reduced tumor growth with combined crizotinib and MMC therapy (p = 0.0088)"',
 'CRC is mentioned once in the list of diseases associated with ROS1 rearrangements: "including glioblastoma, non-small cell lung cancer (NSCLC), cholangiocarcinoma, ovarian cancer, gastric adenocarcinoma, colorectal cancer, inflammatory myofibroblastic tumor, angiosarcoma, and epithelioid hemangioendothelioma"',
 'Crizotinib is mentioned in the context of lung cancer treatment: "Targeting ROS1 fusion proteins with the small-molecule inhibitor crizotinib is showing promise as an effective therapy in patients with NSCLC whose tumors are positive for these genetic abnormalities."',
 'Crizotinib is not being studied for CRC - the article cannot assess its therapeutic efficacy',
 '"colorectal cancer (CRC) cell lines" и "metastatic and orthotopic animal models of colon cancer"',
 '"combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib)" на моделях CRC',
 '"significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer"',
 'Among the responders, patients with CRC were mentioned, but the study did not focus on them. There are no separate models, cell lines or detailed analysis of only this group',
 'Crizotinib is not mentioned in the abstract. Study Evaluates Entrechtinib',
 'The study is evaluating entrechtinib. There is simply no data on the therapeutic efficacy of crizotinib for CRC.',
 'Human colon carcinoma cells and animal models were used',
 'It was indicated that inhibition of the MTH1 enzyme with (S)-crizotinib caused an increase in single-strand DNA breaks and activated DNA repair in human colon carcinoma cells',
 '1) increase in single-strand DNA breaks and activation of DNA repair in colon carcinoma cells 2) effective suppression of tumor growth in animal models',
 'CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab',
 'Crizotinib is mentioned in the abstract, but exclusively in relation to non-small cell lung cancer and the EML4-ALK biomarker',
 'All discussions of the effectiveness of crizotinib apply to NSCLC',
 'CRC is mentioned once in the list of examples: "the use of the monoclonal antibodies (trastuzumab and cetuximab) in HER2-positive breast cancer and wild-type KRAS colorectal cancer"',
 'Crizotinib in the article is associated with CML, GIST and NSCLC',
 'Crizotinib is not being studied for CRC. The article cannot evaluate its therapeutic effectiveness',
 'CRC is mentioned once in the introduction as a general example of malignancies in which rearrangements of receptor tyrosine kinases have been described',
 'Crizotinib is mentioned in the Background section in the context of treating NSCLC',
 'The conclusion makes a general conclusion about the feasibility of studying ROS1 inhibitors (without specifying a specific drug) for a subgroup of patients with gastric cancer',
 'CRC is mentioned as one of the three main tumor types considered in the context of a review of approved drugs (bevacizumab, cetuximab), without presenting its own primary data or models',
 '"FDA-approved drugs like osimertinib and crizotinib... providing remarkable benefits in patients with EGFR-mutated or ALK-positive lung cancer"',
 'All efficacy data mentioned are for either lung cancer (for crizotinib) or CRC (for bevacizumab and cetuximab)',
 'The study focused on CRC. It uses the TCGA and GEO databases containing samples from patients with CRC ("The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival")',
 'Crizotinib is mentioned in the context of computational prediction of drug sensitivity based on gene expression profiles: "drugs such as FTI-277, DMOG, and Crizotinib were more sensitive to low-risk group." This is a bioinformatics procedure (predicting IC50 values \u200b\u200busing algorithms such as pRRophetic) in which the drug is not actually applied to cells or patients, but rather its potential sensitivity is mathematically modeled',
 'The study provides predicted sensitivity but does not report any biologically or clinically relevant outcomes (such as apoptosis, tumor growth inhibition, survival, etc.) in response to crizotinib',
 'The study uses clinically relevant models - 3D CRC cultures ("patient-derived 3D colorectal cancer cultures")',
 'Study testing (S)-enantiomer of crizotinib as an intervention in 3D CRC cultures',
 'Эффективность: "reduce cancer cell viability"; "reduced tyrosine phosphorylation of c-MET and ErbB3"; "induced DNA damage"',
 '"A patient with metastatic BRAF-mutated colorectal cancer" и "In BRAF-mutated colorectal cancer cells"',
 '"the patient was treated with the dual ALK-MET inhibitor crizotinib plus vemurafenib"',
 'Clinical outcome: The patient had a rapid and robust clinical response to the new therapy regimen. Biological/preclinical outcome: The combination of BRAF and MET inhibition (crizotinib) was shown in vitro to overcome acquired resistance to previous therapy',
 'Study describes inflammatory myofibroblastic tumor',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'Study focused on CRC',
 'Crizotinib is being investigated as the active therapeutic component of the Crizotinib-IR808 conjugate. The conjugate is used for chemophototherapy, where crizotinib acts as a chemotherapeutic agent in combination with phototherapy',
 'Study evaluates therapeutic efficacy of crizotinib-containing conjugate based on biologically relevant preclinical outcomes',
 'Study describes a patient with an inflammatory myofibroblastic tumor of the rectoanal region',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 '"the TRKA-dependent colorectal carcinoma KM12"; "Oral administration of entrectinib to tumor-bearing mice induced regression in relevant human xenograft tumors, including the TRKA-dependent colorectal carcinoma KM12"; "objective responses to a TRK inhibitor in colorectal carcinoma"',
 'Crizotinib is mentioned as an example of an already known selective kinase inhibitor, the effectiveness of which has been demonstrated in ALK/ROS1-positive tumors: "selective kinase inhibitors such as crizotinib, ceritinib, and alectinib"',
 'Therapeutic efficacy for CRC has not been assessed',
 'CRC is mentioned once in the abstract in the context that combined BRAF+MEK inhibition is not approved for it (“FDA approved for BRAF V600E-mutant solid tumors except for colorectal cancer”)',
 'Crizotinib is being studied in combination with vemurafenib in the general population (solid tumors in general)',
 'Study evaluates OS, PFS and ORR for entire solid tumor cohort',
 '"The LoVo colon cancer cell line"',
 'Crizotinib applied as an experimental treatment to CRC spheroids',
 'The study evaluates the biological effect of crizotinib in a 3D model of CRC. Although the focus of the article is on validating a new measurement method, the authors demonstrate that treatment with crizotinib has an effect on the biological parameters of the spheroids (changes in mass density and, as a result, structural integrity).',
 'The study included two independent clinical cohorts of patients with CRC (n=363 and n=390), clinical tissue samples ("clinical CRC tissues"), and also included cellular models to assess migration and invasion',
 '"the c-MET inhibitor crizotinib blocked the HGF/STAT3/SOX13/c-MET axis"',
 '"significantly inhibiting SOX13-mediated CRC migration, invasion and metastasis"',
 'The study focuses on hepatocellular carcinoma',
 'Crizotinib is being used and is being studied as an intervention for hepatocellular carcinoma',
 'Because the study does not include CRC nor does it test crizotinib, its therapeutic efficacy for CRC cannot be assessed.',
 'CRC is mentioned once in the list of rare locations where ROS1 fusions can occur',
 '"Crizotinib was the first inhibitor approved... for the treatment of ROS1-positive non-small cell lung cancer"',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'Uses a tissue microarray of colorectal tumors, as well as 3 well-known CRC cell lines with the KRAS mutation: HCT116, DLD1 and LoVo',
 '"used a small molecule inhibitor of c-Met, crizotinib, in cetuximab-resistant, mutant KRAS-driven colorectal cancer cell lines"',
 'The study evaluates biologically and clinically relevant outcomes of crizotinib in combination with radiation. Specific quantitative data provided',
 'Research about CRC. It uses data from The Cancer Genome Atlas (TCGA) specifically for the PTPRK-RSPO3 fusion CRC subtype',
 'Crizotinib was identified through bioinformatics analysis of target-drug networks. The drug has not been tested on cells, animals or patients',
 'Therapeutic efficacy has not been assessed',
 '"RNA sequencing of formalin-fixed, paraffin-embedded (FFPE) cancer tissue samples of 23 CRC patients"',
 '"Patients were treated by... crizotinib... as monotherapy or in combination with chemotherapy"',
 'The abstract provides algorithm quality metrics (AUC, Hazard ratio) for bevacizumab, but does not provide specific data on the actual therapeutic efficacy of crizotinib (for example, ORR, PFS or OS specifically for the crizotinib-treated cohort). The abstract does not allow an unambiguous assessment of the clinical efficacy of crizotinib as such.',
 'CRC is mentioned once in the list of diseases in the pathogenesis of which ALK may play a role',
 'Crizotinib is mentioned in the context of treating NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 '"Thirty-six RASMT metastatic CRC patients were enrolled in the dose expansion"',
 '"assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients"',
 'Эффективность: "Best clinical response within the RASMT CRC cohort was stable disease in seven patients (24%)", "no objective responses observed"',
 '"expression profiles and clinical characteristics of CRC from the Gene Expression Omnibus (GEO) database and the Cancer Genome Atlas (TCGA) database"',
 'The drug is mathematically predicted to be potentially effective for a subgroup of patients at high immune risk (“S-crizotinib might have potential therapeutic implications”)',
 'Therapeutic efficacy has not been assessed',
 'The study represents a general screen of 1402 chemical compounds for their immunomodulatory potential ex vivo on peripheral mononuclear leukocytes. Although T cell interaction with "cancer cells" is mentioned, there is no indication in the abstract that these are CRC cells',
 'Crizotinib is being studied for its immunomodulatory properties (the ability to alter interactions between cells of the immune system)',
 'The study evaluates the effect of crizotinib on immune interactions rather than antitumor activity',
 '"human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 '"Crizotinib are selected to test their cytotoxic effects on human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 'The results indicate that crizotinib exhibits moderate cytotoxicity against CRC Caco-2 cells',
 'Review article on clinical findings and methods for detecting ROS1 in clinical laboratories. Colorectal carcinoma is mentioned once in the list of tumors where ROS1 rearrangements can occur',
 '"crizotinib has been shown to be an effective inhibitor of ROS1 and has received Food and Drug Administration approval for treatment of advanced NSCLC"',
 'Therapeutic efficacy cannot be assessed for CRC',
 'The study includes men with cancer, but there is no mention of CRC in the abstract',
 'The drug is not being studied specifically for CRC',
 'The study evaluates endocrine side effects (levels of total and free testosterone, LH, FSH, androgen deficiency symptoms) rather than antitumor activity',
 '"ARID1A-deficient colorectal cancer (CRC) cells", "in vitro and in xenograft tumor models"',
 '"c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells…"ъ',
 '"selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models", "diminishes GPX4 expression, resulting in elevated lipid peroxidation and glutathione depletion, ultimately inducing ferroptosis"',

In [ ]:
dfo.iloc[:,4:] = np.array([i.text for i in r]).reshape(-1,3)
#dfo.to_csv('/content/drive/MyDrive/new_criteria_ana_en.csv',index=False)